#!/usr/bin/env python3
"""
Bot #17 — Newsletter Generator
Category: Marketing
Purpose: Generate complete, ready-to-send email newsletter issues with all sections,
         subject lines, preview text, and engaging content.
"""
import os
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot  # noqa: E402


class NewsletterBot(BaseBot):

    def __init__(self):
        super().__init__("17_newsletter_generator", "marketing")

    def run(self, newsletter_name: str = None, topic: str = None,
            sections: int = None, tone: str = None,
            include_cta: bool = True, **kwargs):

        cfg = self.config
        newsletter_name = newsletter_name or cfg.get("newsletter_name", "The WheellsVerse Dispatch")
        topic = topic or cfg.get("topic", "AI automation tools and entrepreneurship")
        sections = sections or cfg.get("sections", 4)
        tone = tone or cfg.get("tone", "conversational, insightful, actionable")
        include_cta = cfg.get("include_cta", include_cta)

        self.logger.info(f"Generating newsletter: {newsletter_name} — {topic}")

        system = (
            "You are a top newsletter writer who has built engaged email lists from scratch. "
            "You know that the best newsletters feel like a message from a smart friend — "
            "not a marketing blast. You write with personality, include specific insights "
            "readers can't get elsewhere, and always leave them wanting the next issue. "
            "Open rates above 40% come from consistency, relevance, and genuine value."
        )

        from datetime import datetime as _dt
        current_date = _dt.now().strftime("%B %d, %Y")
        prompt = f"""Write a complete, ready-to-send newsletter issue:

NEWSLETTER NAME: {newsletter_name}
ISSUE DATE: {current_date}
MAIN TOPIC: {topic}
NUMBER OF SECTIONS: {sections}
TONE: {tone}

## HEADER BLOCK
- **Subject Line:** (A version — main option)
- **Subject Line:** (B version — test alternative)
- **Preview Text:** (under 100 chars — the text that shows after subject in inbox)
- **From Name:** [recommended sender name]

## ISSUE INTRO (100-150 words)
Personal, warm opener that references {current_date} or something timely.
Don't start with "Welcome!" — open with something interesting.

## MAIN SECTIONS ({sections} total)

For each section, provide:

### SECTION [N]: [Section Name/Hook Headline]
**Format:** [tip/insight/resource/story/news/tool]
**Content:** (200-300 words of actual content — not placeholders)
Include: specific examples, data points, or actionable steps

---

## QUICK HITS
3-5 bullet points — short, punchy, interesting facts or links from {topic}

## TOOL/RESOURCE OF THE WEEK
One specific tool, book, or resource with:
- What it is
- Why it's useful for this audience
- Where to get it (use a link placeholder)

{"## CALL TO ACTION" if include_cta else "## COMMUNITY QUESTION"}
{"A clear, single ask — what do you want readers to do after reading?" if include_cta else "A thought-provoking question to encourage replies"}

## SIGN-OFF
Warm, on-brand closing with signature

## METADATA FOR EMAIL PLATFORM
- **Segment:** All subscribers (or suggest segments)
- **Send time:** Best day/time recommendation
- **Tags to add:** Based on engagement with this topic"""

        result = self.ai(prompt, system=system,
                         model=os.getenv("OPENAI_MODEL", "gpt-4o"),
                         max_tokens=3000)

        ts = _dt.now().strftime("%Y%m%d_%H%M%S")
        safe_name = newsletter_name.replace(" ", "_")[:25]

        output = f"""# Newsletter Issue: {newsletter_name}
**Date:** {current_date}
**Topic:** {topic}
**Sections:** {sections}
**Generated:** {_dt.now().strftime('%Y-%m-%d %H:%M')}

---

{result}

---
*Generated by WheellsVerse Newsletter Generator Bot*
"""
        path = self.save_output(output, f"newsletter_{safe_name}_{ts}.md", ext="md")
        self.logger.info(f"Newsletter saved → {path}")
        return {"file": str(path), "newsletter": newsletter_name, "topic": topic}


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Newsletter Generator")
    parser.add_argument("--name", type=str, default=None)
    parser.add_argument("--topic", type=str, default=None)
    parser.add_argument("--sections", type=int, default=4)
    parser.add_argument("--tone", type=str, default="conversational, insightful")
    args = parser.parse_args()
    bot = NewsletterBot()
    result = bot.execute(newsletter_name=args.name, topic=args.topic,
                         sections=args.sections, tone=args.tone)
    print(f"\n✅ Newsletter: {result['file']}")
