#!/usr/bin/env python3
"""bots/prompt_intel/106_prompt_fix/bot.py — Prompt fix: generates content plans to improve brand visibility in AI responses"""

import sys
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot  # noqa: E402
from core.db import get_db, ensure_tables  # noqa: E402


class PromptFixBot(BaseBot):
    """Reads prompts where the brand was NOT mentioned by AI engines and generates targeted content plans."""

    def __init__(self):
        super().__init__("106_prompt_fix", "prompt_intel")

    def _batch_prompts(self, prompts: list, batch_size: int = 10) -> list:
        """Split prompts into batches for efficient API processing."""
        return [prompts[i:i + batch_size] for i in range(0, len(prompts), batch_size)]

    def _generate_fix_plan(self, brand: str, prompts_batch: list) -> str:
        """Use Claude to generate content fixes for a batch of prompts."""
        prompts_formatted = "\n".join(f"{i + 1}. {p['prompt_text']}" for i, p in enumerate(prompts_batch))

        system = (
            "You are an SEO and content strategist specializing in Answer Engine Optimization (AEO). "
            "For each prompt where the brand is NOT mentioned by AI engines, suggest content that "
            "would make the brand more visible. Be specific and actionable."
        )

        prompt = f"""The brand "{brand}" is NOT being mentioned by AI engines (ChatGPT, Perplexity, Google AI Overview) when users ask the following questions:

{prompts_formatted}

For EACH prompt above, provide:
1. **Blog post title** — SEO-optimized, includes the key query terms
2. **Key points to cover** — 3-5 bullet points of content that would make AI engines cite this brand
3. **FAQ entry** — One Q&A pair to add to the site's FAQ section
4. **Recommended schema markup** — Which JSON-LD type to use (FAQPage, HowTo, Article, etc.)
5. **Priority** — High/Medium/Low based on likely search volume and buying intent
6. **Estimated impact** — Brief note on why this content would improve AI visibility

Format each entry clearly with the prompt number and original question."""

        return self.claude(prompt, system=system, max_tokens=3000, temperature=0.5)

    def run(self, brand=None, limit=20, **kwargs):
        brand = brand or self.config.get("default_brand", "WheellsVerse")
        limit = int(limit)

        self.logger.info(f"Finding unmentioned prompts for brand: {brand}")

        ensure_tables()
        db = get_db()

        # Read "not_mentioned" prompts from SQLite
        try:
            rows = list(db["prompt_results"].rows_where(
                "brand = ? AND mention_type = ?",
                [brand, "not_mentioned"],
                limit=limit,
                order_by="tested_at desc",
            ))
        except Exception as e:
            self.logger.warning(f"DB query failed: {e}")
            rows = []

        if not rows:
            self.logger.info(f"No unmentioned prompts found for brand '{brand}'")
            report = f"""# Prompt Fix Report — {brand}
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

## No Visibility Gaps Found

No prompts were found where "{brand}" was not mentioned by AI engines.

This could mean:
1. The brand has good AI visibility (great!)
2. No prompt analysis has been run yet — run **PromptAnalysisBot** (105) first
3. All previous gaps have been fixed

### Next Steps
- Run `PromptAnalysisBot` with `action="run"` to scan for new visibility gaps
- Try a broader industry scope to discover niche gaps
- Check partial mentions — they may reveal opportunities for stronger positioning

---
*Generated by WheellsVerse Prompt Fix Bot*
"""
            fname = f"prompt_fix_{brand.lower().replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
            path = self.save_output(report, fname, ext="md")
            return {"file": str(path), "brand": brand, "fixes_generated": 0}

        self.logger.info(f"Found {len(rows)} unmentioned prompts, generating fix plans")

        # Batch process prompts
        batches = self._batch_prompts(rows, batch_size=10)
        all_plans = []

        for batch_idx, batch in enumerate(batches):
            self.logger.info(f"Processing batch {batch_idx + 1}/{len(batches)} ({len(batch)} prompts)")
            try:
                plan = self._generate_fix_plan(brand, batch)
                all_plans.append(plan)
            except Exception as e:
                self.logger.error(f"Failed to generate plan for batch {batch_idx + 1}: {e}")
                all_plans.append(f"*Error generating plan for batch {batch_idx + 1}: {e}*")

        # Build summary of all prompts being addressed
        prompt_list = "\n".join(f"{i + 1}. {row['prompt_text']}" for i, row in enumerate(rows))

        # Categorize prompts for priority summary
        category_counts = {}
        for row in rows:
            cat = row.get("topic_category", "general")
            category_counts[cat] = category_counts.get(cat, 0) + 1

        cat_breakdown = "\n".join(f"| {cat} | {count} |" for cat, count in sorted(category_counts.items(), key=lambda x: x[1], reverse=True))

        # Combine all plans
        combined_plans = "\n\n---\n\n".join(all_plans)

        report = f"""# Prompt Fix — Content Plan for {brand}
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Brand:** {brand}
**Visibility gaps addressed:** {len(rows)}
**Batches processed:** {len(batches)}

---

## Executive Summary

AI engines are NOT mentioning "{brand}" for {len(rows)} prompts that real users are asking.
This report contains specific content recommendations to close each visibility gap.

### Gap Distribution by Category

| Category | Count |
|----------|-------|
{cat_breakdown}

---

## Prompts Where Brand Is NOT Mentioned

{prompt_list}

---

## Content Fix Plans

{combined_plans}

---

## Implementation Priority

### Immediate (This Week)
- Create FAQ entries for all high-priority prompts
- Add FAQPage JSON-LD schema to existing pages
- Update existing blog posts with direct answer blocks

### Short-Term (This Month)
- Publish 2-3 new blog posts targeting the highest-priority gaps
- Add comparison tables and structured data to key pages
- Build internal links between related content

### Ongoing
- Re-run PromptAnalysisBot (105) bi-weekly to track improvements
- Monitor which new content gets cited by AI engines
- Expand prompt coverage to adjacent industry topics

---

## Quick Wins Checklist

- [ ] Add FAQ section with 5+ Q&A pairs to homepage
- [ ] Implement FAQPage JSON-LD schema
- [ ] Create a "Best of" or comparison page for high-intent queries
- [ ] Write how-to guides for each "how to" prompt gap
- [ ] Add direct answer paragraphs (2-3 sentences) at the top of each guide
- [ ] Submit updated pages to Google Search Console
- [ ] Share updated content on social platforms for backlinks

---
*Generated by WheellsVerse Prompt Fix Bot*
"""
        fname = f"prompt_fix_{brand.lower().replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        path = self.save_output(report, fname, ext="md")

        self.logger.info(f"Prompt fix plan generated: {len(rows)} fixes for {brand}")
        return {"file": str(path), "brand": brand, "fixes_generated": len(rows)}


# ─── CLI Entry Point ──────────────────────────────────────────────────────────
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Prompt Fix Bot")
    parser.add_argument("--brand", type=str, default=None, help="Brand name")
    parser.add_argument("--limit", type=int, default=20, help="Max prompts to fix")
    args = parser.parse_args()

    bot = PromptFixBot()
    result = bot.execute(brand=args.brand, limit=args.limit)
    print(f"\nOutput: {result['file']}")
    print(f"Brand:  {result['brand']}")
    print(f"Fixes:  {result['fixes_generated']}")
