#!/usr/bin/env python3
"""
Bot #7 — Keyword Scraper & Researcher
Category: Marketing
Purpose: Generate comprehensive keyword lists with search intent, difficulty estimates,
         content ideas, and cluster mapping for SEO/PPC campaigns.
"""

import os
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot  # noqa: E402


class KeywordScraperBot(BaseBot):

    def __init__(self):
        super().__init__("07_keyword_scraper", "marketing")

    def run(self, seed_keyword: str = None, niche: str = None,
            audience: str = None, num_keywords: int = None,
            include_questions: bool = True, **kwargs):

        cfg = self.config
        seed_keyword = seed_keyword or cfg.get("seed_keyword", "AI automation")
        niche = niche or cfg.get("niche", "AI & technology for business")
        audience = audience or cfg.get("audience", "entrepreneurs, small business owners")
        num_keywords = num_keywords or cfg.get("num_keywords", 50)

        self.logger.info(f"Researching keywords for: '{seed_keyword}'")

        system = (
            "You are an expert SEO analyst and keyword researcher with deep knowledge of "
            "Google's algorithm, search intent, and content strategy. "
            "You provide actionable keyword data that drives real rankings and traffic."
        )

        prompt = f"""Generate a comprehensive keyword research report for:

SEED KEYWORD: {seed_keyword}
NICHE: {niche}
TARGET AUDIENCE: {audience}
NUMBER OF KEYWORDS REQUESTED: {num_keywords}

Provide the following keyword categories:

## 1. HEAD TERMS (High Volume, High Competition) — 5 keywords
Format: | Keyword | Est. Monthly Volume | Difficulty (1-10) | Intent |

## 2. LONG-TAIL KEYWORDS (Lower Volume, Lower Competition) — 20 keywords
Format: | Keyword | Est. Volume | Difficulty | Intent | Content Idea |

## 3. QUESTION KEYWORDS (For FAQ/Featured Snippets) — 15 keywords
Format: | Question | Volume Est. | Content Format |

## 4. BUYER-INTENT KEYWORDS (High Commercial Value) — 10 keywords
Format: | Keyword | Intent | CPC Est. | Priority |

## 5. LOCAL/NICHE-SPECIFIC KEYWORDS — 10 keywords
Format: | Keyword | Specificity | Opportunity |

## 6. KEYWORD CLUSTERS (Group by topic for pillar content)
List 5 clusters, each with 3-5 related keywords

## 7. NEGATIVE KEYWORDS (PPC — keywords to exclude)
List 10 irrelevant keywords to exclude from paid campaigns

## 8. CONTENT CALENDAR SUGGESTION
Map top 10 keywords to content types and recommended publish schedule

## 9. QUICK WINS
Top 5 keywords you can rank for within 30-60 days (low competition, decent volume)

## 10. MONETIZATION KEYWORDS
Top 5 keywords with highest affiliate/CPC potential

Use realistic search volume estimates for 2024-2025.
Mark search intent as: Informational | Navigational | Commercial | Transactional"""

        research = self.ai(prompt, system=system, model=os.getenv("OPENAI_MODEL_FAST", "gpt-4o-mini"), max_tokens=3000)

        # Also generate JSON version for programmatic use
        json_prompt = f"""Based on this seed keyword: "{seed_keyword}"
Generate a JSON array of 20 keywords with this exact structure:
[
  {{
    "keyword": "example keyword phrase",
    "volume_estimate": 1000,
    "difficulty": 5,
    "intent": "informational",
    "content_type": "blog_post",
    "priority": "high"
  }}
]
Return ONLY the JSON array, no other text."""

        keywords_json = self.ai_json(json_prompt, system="Return only valid JSON arrays.")

        output = f"""# Keyword Research Report
**Seed Keyword:** {seed_keyword}
**Niche:** {niche}
**Audience:** {audience}
**Generated:** {self._now()}

---

{research}

---
*Generated by WheellsVerse Keyword Scraper Bot*
"""
        safe = seed_keyword.replace(" ", "_")[:30]
        path = self.save_output(output, f"keywords_{safe}.md", ext="md")
        json_path = self.save_json(
            {"seed": seed_keyword, "keywords": keywords_json},
            f"keywords_{safe}.json"
        )
        self.logger.info(f"Keywords saved → {path}")
        return {"file": str(path), "json_file": str(json_path),
                "seed_keyword": seed_keyword}

    def _now(self):
        from datetime import datetime
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Keyword Scraper Bot")
    parser.add_argument("--keyword", type=str, default=None)
    parser.add_argument("--niche", type=str, default=None)
    parser.add_argument("--count", type=int, default=50)
    args = parser.parse_args()
    bot = KeywordScraperBot()
    result = bot.execute(seed_keyword=args.keyword, niche=args.niche,
                         num_keywords=args.count)
    print(f"\n✅ Keywords: {result['file']}")
