#!/usr/bin/env python3
"""
Bot #99 — AI Engineer Bot
Category: Agent Workforce
Purpose: Code review, generation, and bug fixing powered by Claude.
         Reads files from disk, analyzes code, and produces actionable output.
"""

import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot  # noqa: E402


class EngineerBot(BaseBot):
    """AI engineer  code review, generation, and fixes powered by Claude."""

    def __init__(self):
        super().__init__("99_engineer_bot", "agent_workforce")

    def _read_file(self, file_path: str) -> str:
        """Safely read a file from disk and return its contents."""
        p = Path(file_path)
        if not p.exists():
            self.logger.warning(f"File not found: {file_path}")
            return f"[File not found: {file_path}]"
        try:
            content = p.read_text(encoding="utf-8", errors="replace")
            # Truncate very large files to avoid token limits
            max_chars = 15000
            if len(content) > max_chars:
                content = content[:max_chars] + f"\n\n... [truncated, {len(content)} total chars]"
            return content
        except Exception as e:
            self.logger.error(f"Error reading {file_path}: {e}")
            return f"[Error reading file: {e}]"

    def run(self, action: str = "review", code: str = None,
            language: str = "python", file_path: str = None,
            description: str = None, **kwargs):

        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        ts_display = datetime.now().strftime("%Y-%m-%d %H:%M")

        # If file_path is given, read the file content
        if file_path:
            self.logger.info(f"Reading file: {file_path}")
            code = self._read_file(file_path)
            # Try to detect language from extension
            ext_map = {
                ".py": "python", ".js": "javascript", ".ts": "typescript",
                ".go": "go", ".rs": "rust", ".rb": "ruby", ".java": "java",
                ".cpp": "c++", ".c": "c", ".sh": "bash", ".sql": "sql",
                ".html": "html", ".css": "css", ".jsx": "jsx", ".tsx": "tsx",
            }
            suffix = Path(file_path).suffix.lower()
            language = ext_map.get(suffix, language)

        # ── Review ──────────────────────────────────────────────────────────
        if action == "review":
            code = code or 'def add(a, b):\n    return a + b\n\nprint(add("1", 2))'

            self.logger.info(f"Reviewing {language} code ({len(code)} chars)")

            system = (
                "You are a senior software engineer and code reviewer with 15+ years "
                "of experience. You review code for: bugs, security vulnerabilities, "
                "performance issues, readability, best practices, and maintainability. "
                "Be specific and actionable. For each issue, provide the line/section, "
                "severity (critical/warning/info), and a concrete fix."
            )

            prompt = f"""Review the following {language} code:

```{language}
{code}
```

Provide a structured code review with:

## Summary
[1-2 sentence overall assessment]

## Issues Found

For each issue:
### [Severity: CRITICAL / WARNING / INFO] [Title]
**Location:** [line or section]
**Problem:** [what's wrong]
**Fix:** [concrete code fix]

## Security Check
[Any security concerns]

## Performance Notes
[Any performance improvements]

## Refactoring Suggestions
[Structural improvements for maintainability]

## Improved Version
```{language}
[Rewritten code with all fixes applied]
```"""

            result = self.claude(prompt, system=system, max_tokens=2500)

            source_label = f"File: {file_path}" if file_path else "Inline code"
            output = f"""# Code Review Report
**Language:** {language}
**Source:** {source_label}
**Generated:** {ts_display}

---

{result}

---
*Generated by WheellsVerse Engineer Bot*
"""
            fname = f"review_{language}_{ts}.md"
            path = self.save_output(output, fname, ext="md")
            return {"file": str(path), "action": action, "language": language}

        # ── Snippet / Generate ──────────────────────────────────────────────
        elif action == "snippet":
            description = description or "A function that retries an HTTP request with exponential backoff"

            self.logger.info(f"Generating {language} snippet: {description[:60]}")

            system = (
                "You are an expert software engineer. You write clean, production-ready "
                "code with proper error handling, type hints (where applicable), "
                "docstrings, and inline comments for complex logic. You follow the "
                "language's idioms and best practices."
            )

            prompt = f"""Generate {language} code for the following:

DESCRIPTION: {description}

Requirements:
1. Production-ready  not a toy example
2. Proper error handling
3. Type hints / annotations where applicable
4. Docstring explaining usage
5. Example usage at the bottom

Return:
## Implementation
```{language}
[the code]
```

## How to Use
[Brief usage examples]

## Dependencies
[Any packages needed, or "None  standard library only"]

## Notes
[Any important caveats or alternatives]"""

            result = self.claude(prompt, system=system, max_tokens=2500)

            output = f"""# Generated Code Snippet
**Language:** {language}
**Description:** {description}
**Generated:** {ts_display}

---

{result}

---
*Generated by WheellsVerse Engineer Bot*
"""
            fname = f"snippet_{language}_{ts}.md"
            path = self.save_output(output, fname, ext="md")
            return {"file": str(path), "action": action, "language": language}

        # ── Fix ─────────────────────────────────────────────────────────────
        elif action == "fix":
            code = code or 'def divide(a, b):\n    return a / b\n\nresult = divide(10, 0)'

            self.logger.info(f"Fixing {language} code ({len(code)} chars)")

            system = (
                "You are a debugging expert. You analyze broken code, identify the "
                "root cause of bugs, and provide working fixes. You explain what went "
                "wrong and why your fix works. You also add defensive coding to prevent "
                "similar issues in the future."
            )

            prompt = f"""The following {language} code has bugs. Identify and fix them.

```{language}
{code}
```

Provide:

## Bug Analysis

For each bug:
### Bug [N]: [Title]
**Root Cause:** [what's wrong and why]
**Impact:** [what happens when this bug triggers]
**Fix:** [the specific change needed]

## Fixed Code
```{language}
[Complete fixed version with all bugs resolved]
```

## What Changed
[Bullet list of every change made and why]

## Prevention Tips
[How to avoid these bugs in the future]"""

            result = self.claude(prompt, system=system, max_tokens=2500)

            source_label = f"File: {file_path}" if file_path else "Inline code"
            output = f"""# Bug Fix Report
**Language:** {language}
**Source:** {source_label}
**Generated:** {ts_display}

---

{result}

---
*Generated by WheellsVerse Engineer Bot*
"""
            fname = f"fix_{language}_{ts}.md"
            path = self.save_output(output, fname, ext="md")
            return {"file": str(path), "action": action, "language": language}

        else:
            raise ValueError(f"Unknown action: {action}. Use review, snippet, or fix.")


# ─── CLI Entry Point ──────────────────────────────────────────────────────────
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="AI Engineer Bot")
    parser.add_argument("--action", type=str, default="review",
                        choices=["review", "snippet", "fix"])
    parser.add_argument("--code", type=str, default=None)
    parser.add_argument("--language", type=str, default="python")
    parser.add_argument("--file", type=str, default=None, dest="file_path")
    parser.add_argument("--description", type=str, default=None)
    args = parser.parse_args()

    bot = EngineerBot()
    result = bot.execute(action=args.action, code=args.code,
                         language=args.language, file_path=args.file_path,
                         description=args.description)
    print(f"\nOutput: {result['file']}")
    print(f"Action: {result['action']}  |  Language: {result['language']}")
