"""§32 Holding-scoped typed memory with a mandatory-provenance write GATE.

Persists to its OWN durable table (``holding_memories``), following the proposals_store /
cycle_store pattern (self-creating table, fail-soft, never raises). It deliberately does NOT
reuse the shared ``memories`` table: that table's ``user_id`` has a FOREIGN KEY to
``profiles(id)`` (alembic 0003), so writing holding rows under a synthetic holding-namespace
user_id would FK-violate in production (no matching profiles row) and be silently lost. The own
table carries no such FK and stores the 7 typed categories + full provenance as real columns.
On top of that durable substrate it adds:
  - a HOLDING scope (holding-wide, not per-user);
  - 7 typed categories (FACT / DECISION / MISSION / PREFERENCE / INCIDENT / ENGINEERING / COMPANY);
  - a write GATE (§32 / §0 #16-19): every write needs provenance; a verified FACT needs an
    ``evidence_ref``; an LLM- or EXTERNAL-sourced claim can NEVER be silently stored as a verified
    FACT — it is refused there and belongs as an UNVERIFIED observation in a non-FACT category,
    or is re-recorded (post-verification) as an evidence-backed OUTCOME.

Verified outcomes are recordable (``record_outcome``) so future decisions can learn from real
results. Bounded / event-driven (§79) — there is no loop here, only single writes and reads.
(Vector similarity search over these rows can be added later; durable typed provenance-gated
storage is the Phase-2 requirement.)

The store is INJECTABLE (the ``put``/``query`` seam) so the GATE is testable with a fake
in-memory store and NO live DB — see ``InMemoryHoldingStore`` and ``test_holding_memory.py``.
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional, Protocol

logger = logging.getLogger(__name__)


class HoldingMemoryError(ValueError):
    """Raised when the write GATE refuses a write (bad category, missing provenance/evidence,
    or an attempt to launder an unverified LLM/EXTERNAL claim into a verified FACT)."""


class MemoryCategory(str, Enum):
    FACT = "FACT"                # a verified truth (requires evidence + a trusted origin)
    DECISION = "DECISION"        # an owner/KAI decision and its rationale
    MISSION = "MISSION"          # mission objective/state notes
    PREFERENCE = "PREFERENCE"    # owner preferences
    INCIDENT = "INCIDENT"        # something that went wrong + context
    ENGINEERING = "ENGINEERING"  # engineering knowledge / how-a-thing-works
    COMPANY = "COMPANY"          # per-company knowledge


class Origin(str, Enum):
    OBSERVED = "OBSERVED"    # read from a real system / tool / registry  (trusted)
    DERIVED = "DERIVED"      # deterministically computed from real data  (trusted)
    OPERATOR = "OPERATOR"    # stated by the owner                        (trusted, authoritative)
    OUTCOME = "OUTCOME"      # a verified result of an action (evidence)  (trusted)
    LLM = "LLM"             # generated by a language model              (UNTRUSTED until verified)
    EXTERNAL = "EXTERNAL"    # 3rd-party / customer / web / repo content  (UNTRUSTED)


class Verification(str, Enum):
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"


# Origins that a verified claim may rest on. LLM/EXTERNAL are deliberately excluded — the model's
# own generation (or untrusted 3rd-party text) is never itself proof (§32/§76).
_TRUSTED = {Origin.OBSERVED, Origin.DERIVED, Origin.OPERATOR, Origin.OUTCOME}
_UNTRUSTED = {Origin.LLM, Origin.EXTERNAL}


def _verify(category: MemoryCategory, origin: Origin, evidence_ref: str) -> Verification:
    """The GATE core. Returns the DERIVED verification status, or raises HoldingMemoryError.

    The verification status is NEVER trusted from the caller — it is derived here from
    (category, origin, evidence_ref) so a caller cannot self-declare a claim "VERIFIED".
    """
    has_ev = bool(evidence_ref and str(evidence_ref).strip())
    if category is MemoryCategory.FACT:
        if origin in _UNTRUSTED:
            raise HoldingMemoryError(
                f"refused: a {origin.value}-sourced claim cannot be stored as a verified FACT. "
                "Record it as an UNVERIFIED observation in a non-FACT category, or verify it "
                "first and record the evidence-backed OUTCOME (§32/§0 #17-19).")
        if not has_ev:
            raise HoldingMemoryError(
                "refused: a FACT requires an evidence_ref — no provenance, no verified fact (§0 #16).")
        return Verification.VERIFIED
    # Non-FACT categories may be recorded, but are VERIFIED only with a trusted origin AND evidence;
    # otherwise they are honestly UNVERIFIED (never silently upgraded).
    return Verification.VERIFIED if (origin in _TRUSTED and has_ev) else Verification.UNVERIFIED


def _as_category(c: Any) -> MemoryCategory:
    if isinstance(c, MemoryCategory):
        return c
    try:
        return MemoryCategory(str(c).upper())
    except Exception:
        raise HoldingMemoryError(
            f"invalid category {c!r}; must be one of {[m.value for m in MemoryCategory]}")


def _as_origin(o: Any) -> Origin:
    if isinstance(o, Origin):
        return o
    try:
        return Origin(str(o).upper())
    except Exception:
        raise HoldingMemoryError(
            f"invalid origin {o!r} (provenance required); must be one of {[m.value for m in Origin]}")


def _scan_untrusted(content: str, origin: Origin) -> bool:
    """Reuse the certified injection scanner (§76) to FLAG untrusted content on write. This never
    blocks the write and never confers trust — the text is data either way; the flag is for audit /
    safe rendering downstream. Fail-open: any scanner failure → not-flagged, never a crash."""
    if origin not in _UNTRUSTED:
        return False
    try:
        from app.services.capability.results import scan_for_injection
        return bool(scan_for_injection(content))
    except Exception:
        return False


@dataclass
class HoldingMemoryRecord:
    category: MemoryCategory
    content: str
    origin: Origin
    verification: Verification
    company: str = ""            # holding entity id, or "" for holding-wide
    evidence_ref: str = ""
    source: str = ""             # specific source label (tool id, doc ref, "owner", ...)
    observed_at: str = ""        # ISO-8601 UTC
    tags: tuple = ()
    injection_flagged: bool = False
    id: Optional[str] = None

    def to_meta(self) -> dict:
        """The typed fields as a plain dict — the serialized shape returned by ``query`` and stored by
        the in-memory fake. The durable store persists these same fields as real columns."""
        return {
            "scope": "holding",
            "category": self.category.value,
            "origin": self.origin.value,
            "verification": self.verification.value,
            "company": self.company,
            "evidence_ref": self.evidence_ref,
            "source": self.source,
            "observed_at": self.observed_at,
            "tags": list(self.tags),
            "injection_flagged": self.injection_flagged,
        }


class HoldingMemoryStore(Protocol):
    """Injectable persistence seam. The production impl is DbHoldingStore (own durable table); the
    test/DB-free impl is InMemoryHoldingStore. The GATE runs BEFORE ``put`` is ever called, so
    refusals never touch persistence."""
    def put(self, record: HoldingMemoryRecord) -> Optional[str]: ...
    def query(self, *, category: Optional[str] = None, company: Optional[str] = None,
              limit: int = 50) -> list[dict]: ...


# ── the dedicated own table (NO profiles FK, unlike the shared `memories` table) ──────────────────
# Typed provenance-gated holding memories, one row each. Self-creating (proposals_store style).
# tags is a JSONB array; all provenance fields are real columns so recall/verified_only filter in SQL.
_DDL = """CREATE TABLE IF NOT EXISTS holding_memories (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    scope TEXT NOT NULL DEFAULT 'holding',
    category TEXT NOT NULL,
    content TEXT NOT NULL,
    origin TEXT NOT NULL,
    verification TEXT NOT NULL,
    company TEXT NOT NULL DEFAULT '',
    evidence_ref TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL DEFAULT '',
    observed_at TEXT NOT NULL DEFAULT '',
    tags JSONB NOT NULL DEFAULT '[]',
    injection_flagged BOOLEAN NOT NULL DEFAULT false
)"""


class DbHoldingStore:
    """Default store — its OWN durable ``holding_memories`` table on App B's Postgres, following the
    proposals_store / cycle_store pattern (self-creating, fail-soft, never raises). It does NOT touch
    the shared ``memories`` table (whose ``user_id`` FK to profiles(id) would reject holding rows)."""

    def _ensure(self, db) -> None:
        from sqlalchemy import text
        db.execute(text(_DDL))

    def put(self, rec: HoldingMemoryRecord) -> Optional[str]:
        try:
            from sqlalchemy import text
            from app.database import SessionLocal
            db = SessionLocal()
            try:
                self._ensure(db)
                r = db.execute(text(
                    "INSERT INTO holding_memories "
                    "(scope, category, content, origin, verification, company, evidence_ref, source,"
                    " observed_at, tags, injection_flagged) "
                    "VALUES ('holding', :cat, :content, :origin, :ver, :company, :ev, :src, :obs,"
                    " CAST(:tags AS JSONB), :flag) RETURNING id"),
                    {"cat": rec.category.value, "content": rec.content, "origin": rec.origin.value,
                     "ver": rec.verification.value, "company": rec.company, "ev": rec.evidence_ref,
                     "src": rec.source, "obs": rec.observed_at, "tags": json.dumps(list(rec.tags)),
                     "flag": rec.injection_flagged}).fetchone()
                db.commit()
                return str(r[0]) if r else None
            finally:
                db.close()
        except Exception:
            # §0 #8: fail SOFT (never crash the caller) but NEVER silent — surface the failure so an
            # operator sees holding-memory persistence is broken (DB down / not migrated).
            logger.warning("holding_memory: durable put failed, memory not persisted", exc_info=True)
            return None

    def query(self, *, category=None, company=None, limit=50) -> list[dict]:
        try:
            from sqlalchemy import text
            from app.database import SessionLocal
            db = SessionLocal()
            try:
                self._ensure(db)
                sql = ("SELECT id, scope, category, content, origin, verification, company, evidence_ref,"
                       " source, observed_at, tags, injection_flagged FROM holding_memories"
                       " WHERE scope = 'holding'")
                params: dict = {"lim": max(1, int(limit))}
                if category:
                    sql += " AND category = :cat"; params["cat"] = category
                if company:
                    sql += " AND company = :company"; params["company"] = company
                sql += " ORDER BY id DESC LIMIT :lim"
                rows = db.execute(text(sql), params).fetchall()
                out: list[dict] = []
                for r in rows:
                    tags = r[10] if isinstance(r[10], list) else json.loads(r[10] or "[]")
                    out.append({"scope": r[1], "category": r[2], "content": r[3], "origin": r[4],
                                "verification": r[5], "company": r[6], "evidence_ref": r[7],
                                "source": r[8], "observed_at": r[9], "tags": tags,
                                "injection_flagged": bool(r[11]), "id": str(r[0])})
                return out
            finally:
                db.close()
        except Exception:
            logger.warning("holding_memory: durable query failed, returning empty", exc_info=True)
            return []


class InMemoryHoldingStore:
    """Fake store (mirrors manual_cycle.InMemoryCycleStore) — the injectable seam for tests and any
    DB-free caller. No embeddings, no DB, no network."""

    def __init__(self):
        self.rows: list[dict] = []
        self._n = 0

    def put(self, rec: HoldingMemoryRecord) -> str:
        self._n += 1
        d = rec.to_meta()
        d["content"] = rec.content
        d["id"] = str(self._n)
        self.rows.append(d)
        return d["id"]

    def query(self, *, category=None, company=None, limit=50) -> list[dict]:
        out = [r for r in reversed(self.rows)
               if (category is None or r.get("category") == category)
               and (company is None or r.get("company") == company)]
        return out[:limit]


class HoldingMemory:
    """The holding-scoped typed memory service. All writes pass the provenance GATE."""

    def __init__(self, store: HoldingMemoryStore | None = None, *,
                 holding_id: str = "wheellsverse", clock=None):
        self._store = store if store is not None else DbHoldingStore()
        self._holding = holding_id
        self._clock = clock or (lambda: datetime.now(timezone.utc).isoformat())

    def write(self, *, category: Any, content: str, origin: Any, evidence_ref: str = "",
              company: str = "", source: str = "", tags=()) -> HoldingMemoryRecord:
        """Gate + persist one memory. Raises HoldingMemoryError if the GATE refuses; the persisted
        record's ``verification`` is DERIVED, never taken from the caller."""
        category = _as_category(category)          # typing enforced
        origin = _as_origin(origin)                # provenance required
        if not (content and content.strip()):
            raise HoldingMemoryError("refused: content cannot be empty")
        verification = _verify(category, origin, evidence_ref)   # the GATE
        rec = HoldingMemoryRecord(
            category=category, content=content.strip(), origin=origin, verification=verification,
            company=company or "", evidence_ref=str(evidence_ref or ""), source=source or "",
            observed_at=self._clock(), tags=tuple(tags or ()),
            injection_flagged=_scan_untrusted(content, origin))
        rec.id = self._store.put(rec)
        return rec

    def record_outcome(self, *, content: str, evidence_ref: str, decision_ref: str = "",
                       mission_ref: str = "", company: str = "",
                       category: Any = MemoryCategory.DECISION) -> HoldingMemoryRecord:
        """Record a VERIFIED outcome (origin=OUTCOME, evidence required) so future decisions can learn
        from real results. Defaults to the DECISION category; may target MISSION or FACT."""
        if not (evidence_ref and str(evidence_ref).strip()):
            raise HoldingMemoryError("refused: an outcome must carry an evidence_ref")
        tags = tuple(t for t in (
            f"decision:{decision_ref}" if decision_ref else "",
            f"mission:{mission_ref}" if mission_ref else "") if t)
        return self.write(category=category, content=content, origin=Origin.OUTCOME,
                          evidence_ref=evidence_ref, company=company, source="verified-outcome",
                          tags=tags)

    def recall(self, *, category: Any = None, company: Optional[str] = None,
               verified_only: bool = False, limit: int = 50) -> list[dict]:
        cat = _as_category(category).value if category is not None else None
        rows = self._store.query(category=cat, company=company, limit=limit)
        if verified_only:
            rows = [r for r in rows if r.get("verification") == Verification.VERIFIED.value]
        return rows

    def recall_outcomes(self, *, company: Optional[str] = None, limit: int = 50) -> list[dict]:
        """Verified prior outcomes (evidence-backed) for learning — never the unverified chatter."""
        return [r for r in self._store.query(company=company, limit=500)
                if r.get("origin") == Origin.OUTCOME.value][:limit]
