#!/usr/bin/env python3
"""
bots/specialized/76_crypto_affiliate_booster/bot.py
Crypto-focused affiliate content and campaign generator.
Revenue goal: Drive Coinbase signups and crypto product conversions.
"""
import os
import sys
import random
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot  # noqa: E402

# OLD constants block read AFFILIATE_<X>_URL from .env with /go/{partner}
# OLD fallbacks. Per affiliate_swap_pass2_2026_06_02 every CTA now
# OLD routes to the owned digital product / blog with UTM tagging.
_BOT = "76_crypto_affiliate_booster"
_CAMP = "affiliate_swap_pass2_2026_06_02"
_DIGITAL = "https://stan.store/Wheellsverse"
_BLOG = "https://wheellsverse.com/blog/"


def _utm(content: str, medium: str = "content", base: str = _DIGITAL) -> str:
    return f"{base}?utm_source={_BOT}&utm_medium={medium}&utm_campaign={_CAMP}&utm_content={content}"


# OLD: COINBASE_URL = os.getenv("AFFILIATE_COINBASE_URL", "https://app.wheellsverse.com/go/coinbase")
COINBASE_URL = _utm("coinbase")
# OLD: ROBINHOOD_URL = os.getenv("AFFILIATE_WEBULL_URL", "https://app.wheellsverse.com/go/webull")
WEBULL_URL = _utm("webull")
AMAZON_TAG = os.getenv("AFFILIATE_AMAZON_TAG", "wheellsverse-20")

CRYPTO_ANGLES = [
    "Coinbase vs Kraken vs Binance: which exchange should you use?",
    "How to buy your first $50 of Bitcoin on Coinbase — step by step",
    "My honest Coinbase review after 2 years of using it",
    "The best crypto exchange for beginners in 2025 — compared",
    "How to set up crypto staking on Coinbase and earn passive income",
    "Coinbase vs Robinhood for crypto: which is better?",
    "How to dollar-cost average into crypto using Coinbase",
    "Crypto exchange security: how Coinbase protects your funds",
    "How I earned $200 in crypto referral bonuses — a real breakdown",
    "The beginner's guide to buying crypto safely in 2025",
    "Is Coinbase safe? An honest look at security and reliability",
    "How to use Coinbase Advanced for lower fees",
]


class CryptoAffiliateBoosterBot(BaseBot):
    """Generates high-converting crypto affiliate content with specific platform focus."""

    def __init__(self):
        super().__init__("76_crypto_affiliate_booster", "specialized")

    def run(self, topic: str = None, platform_focus: str = "coinbase", **kwargs):
        cfg = self.config
        topic = topic or cfg.get("default_topic") or random.choice(CRYPTO_ANGLES)
        platform_focus = platform_focus or cfg.get("platform_focus", "coinbase")
        self.logger.info(f"Running {self.name}: {topic}")

        system_str = (
            "You are a cryptocurrency product reviewer and affiliate marketer. "
            "You write honest, detailed reviews and comparisons of crypto platforms. "
            "Your readers trust your opinions because you back them with real experience "
            "and specific details — not vague praise. You acknowledge limitations alongside "
            "strengths. Your affiliate recommendations always solve a specific reader problem."
        )

        prompt = f"""Write a detailed, conversion-optimized crypto affiliate piece on: "{topic}"

## Primary Affiliate Links
- **Coinbase** ({COINBASE_URL}): Get $10 in BTC when you sign up and buy $100+
- **Robinhood** ({WEBULL_URL}): Trade crypto + stocks with no commissions
# OLD: - **Crypto books** (https://www.amazon.com/s?k=cryptocurrency+2025&tag={AMAZON_TAG}): Learning resources
- **Crypto books** ({_utm('amazon_crypto')}): Learning resources

## Focus Platform: {platform_focus.title()}

## Content Structure

**1. Attention-Grabbing Headline** (specific, includes the platform name or comparison)

**2. Credibility Hook** (1-2 sentences establishing why you're the right person to write this)

**3. Main Review/Content** (600-800 words):
   - Specific features with real descriptions (not marketing speak)
   - Who this is best for (and who should look elsewhere)
   - Fee structure explained clearly
   - Security and trust signals
   - Beginner vs advanced usability
   - Honest verdict

**4. Side-by-Side Comparison Table** (if applicable):
   | Feature | Coinbase | Robinhood | Kraken |
   | Fees | | | |
   | Crypto selection | | | |
   | Ease of use | | | |

**5. Signup Bonus Section** (feature any current offers prominently)

**6. Final Recommendation** + affiliate CTA with specific link text

Make it feel like trusted advice, not a sales pitch."""

        result = self.ai(
            prompt, system=system_str,
            model=os.getenv("OPENAI_MODEL", "gpt-4o"),
            max_tokens=2500
        )

        from datetime import datetime as _dt
        ts = _dt.now().strftime("%Y%m%d_%H%M%S")
        safe_topic = "".join(c if c.isalnum() else "_" for c in topic[:40])

        output = f"""# {topic}
*Platform Focus: {platform_focus.title()} | Generated: {_dt.now().strftime('%Y-%m-%d %H:%M')}*

---

{result}

---
*Generated by WheellsVerse Crypto Affiliate Booster — {self.name}*
"""
        path = self.save_output(output, f"crypto_affiliate_{safe_topic}_{ts}.md", ext="md")
        self.logger.info(f"Saved: {path}")
        return {"file": str(path), "topic": topic, "platform": platform_focus, "bot": self.name}


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Crypto Affiliate Booster Bot")
    parser.add_argument("--topic", type=str, default=None, help="Crypto affiliate topic")
    parser.add_argument("--platform", type=str, default="coinbase",
                        choices=["coinbase", "webull", "comparison", "general"])
    args = parser.parse_args()
    bot = CryptoAffiliateBoosterBot()
    result = bot.execute(topic=args.topic, platform_focus=args.platform)
    print(f"\n✅ Output: {result['file']}")
