#!/usr/bin/env python3
"""bots/seo_autopilot/113_publisher/bot.py — SEO publisher"""
import os
import sys
import shutil
import re
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot  # noqa: E402


class SEOPublisherBot(BaseBot):
    """Publishes SEO articles to WordPress or copies them to local blog directories."""

    def __init__(self):
        super().__init__("113_publisher", "seo_autopilot")

    def run(self, file_path=None, platform=None, title=None, **kwargs):
        cfg = self.config
        platform = platform or cfg.get("default_platform", "local")

        if not file_path:
            self.logger.error("file_path is required")
            raise ValueError("file_path is required to publish an article")

        src = Path(file_path)
        if not src.exists():
            self.logger.error(f"File not found: {file_path}")
            raise FileNotFoundError(f"File not found: {file_path}")

        content = src.read_text(encoding="utf-8")

        # Extract title from frontmatter or H1 if not provided
        if not title:
            fm_match = re.search(r"^---.*?title:\s*(.+?)\s*\n.*?---", content, re.DOTALL)
            if fm_match:
                title = fm_match.group(1).strip()
            else:
                h1_match = re.search(r"^#\s+(.+)", content, re.MULTILINE)
                title = h1_match.group(1).strip() if h1_match else src.stem

        self.logger.info(f"Publishing '{title}' to platform: {platform}")

        published_path = None
        status = "failed"

        if platform == "wordpress":
            published_path, status = self._publish_wordpress(src, content, title)
        else:
            # Default to local for unknown platforms too
            platform = "local"
            published_path, status = self._publish_local(src, content, title)

        # Update SQLite articles status
        try:
            from core.db import get_db
            db = get_db()
            now = datetime.now().isoformat()
            # Try to update existing record by matching on filename/title
            existing = list(db["articles"].rows_where(
                "keyword = ? OR keyword LIKE ?",
                [title, f"%{src.stem}%"]
            )) if "articles" in db.table_names() else []
            if existing:
                db["articles"].update(existing[0]["id"], {
                    "status": status,
                    "published_at": now,
                    "published_path": str(published_path),
                    "updated_at": now,
                })
                self.logger.info("Updated article status in SQLite")
            else:
                db["articles"].insert({
                    "keyword": title,
                    "status": status,
                    "published_at": now,
                    "published_path": str(published_path),
                    "created_at": now,
                    "updated_at": now,
                }, alter=True)
                self.logger.info("Inserted new article record in SQLite")
        except Exception as e:
            self.logger.warning(f"Could not update SQLite articles table: {e}")

        # Generate markdown publish report
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        report_lines = [
            "# Publish Report",
            f"**Date:** {ts}",
            f"**Title:** {title}",
            f"**Source File:** {file_path}",
            f"**Platform:** {platform}",
            f"**Status:** {status}",
            f"**Published Path:** {published_path}",
            "",
            "---",
            "",
        ]

        if status == "published":
            report_lines += [
                "## Result",
                "",
                f"Article successfully published to **{platform}**.",
                "",
                f"- Source: `{src.name}`",
                f"- Destination: `{published_path}`",
                f"- Published at: {ts}",
            ]
        else:
            report_lines += [
                "## Result",
                "",
                "Publication failed or fell back to local. Check logs for details.",
            ]

        report_lines.append("")
        report_lines.append("*Generated by WheellsVerse SEO Publisher Bot*")

        report = "\n".join(report_lines)
        report_ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_title = re.sub(r"[^\w]+", "_", title.lower())[:40]
        report_fname = f"publish_report_{safe_title}_{report_ts}.md"
        report_path = self.save_output(report, report_fname, ext="md")

        self.logger.info(f"Publish report saved -> {report_path}")
        return {
            "file": str(report_path),
            "platform": platform,
            "status": status,
            "published_path": str(published_path),
        }

    # ──────────────────────────────────────────────────────────────────────────
    # Private helpers
    # ──────────────────────────────────────────────────────────────────────────

    def _publish_local(self, src: Path, content: str, title: str):
        """Copy article to outputs/published/ and frontend/blog/."""
        root = self.root_dir

        # outputs/published/
        published_dir = root / "outputs" / "published"
        published_dir.mkdir(parents=True, exist_ok=True)
        dest_published = published_dir / src.name
        shutil.copy2(src, dest_published)
        self.logger.info(f"Copied to outputs/published/ -> {dest_published}")

        # frontend/blog/
        blog_dir = root / "frontend" / "blog"
        blog_dir.mkdir(parents=True, exist_ok=True)
        dest_blog = blog_dir / src.name
        shutil.copy2(src, dest_blog)
        self.logger.info(f"Copied to frontend/blog/ -> {dest_blog}")

        return dest_blog, "published"

    def _publish_wordpress(self, src: Path, content: str, title: str):
        """POST article to WordPress REST API."""
        wp_url = os.getenv("WORDPRESS_URL", "")
        wp_user = os.getenv("WORDPRESS_USER", "")
        wp_pass = os.getenv("WORDPRESS_APP_PASS", "")

        if not (wp_url and wp_user and wp_pass):
            self.logger.warning(
                "WordPress env vars (WORDPRESS_URL, WORDPRESS_USER, WORDPRESS_APP_PASS) "
                "not fully set — falling back to local publish"
            )
            return self._publish_local(src, content, title)

        try:
            import requests
            import base64

            # Strip YAML frontmatter for WordPress body
            body = re.sub(r"^---.*?---\s*", "", content, flags=re.DOTALL).strip()

            endpoint = wp_url.rstrip("/") + "/wp-json/wp/v2/posts"
            credentials = base64.b64encode(f"{wp_user}:{wp_pass}".encode()).decode()
            headers = {
                "Authorization": f"Basic {credentials}",
                "Content-Type": "application/json",
            }
            payload = {
                "title": title,
                "content": body,
                "status": "publish",
            }
            resp = requests.post(endpoint, json=payload, headers=headers, timeout=30)
            resp.raise_for_status()
            post_data = resp.json()
            post_url = post_data.get("link", wp_url)
            self.logger.info(f"Published to WordPress: {post_url}")
            return post_url, "published"

        except Exception as e:
            self.logger.error(f"WordPress publish failed: {e} — falling back to local")
            return self._publish_local(src, content, title)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--file", required=True, help="Path to markdown article")
    parser.add_argument("--platform", default="local")
    parser.add_argument("--title", default=None)
    args = parser.parse_args()

    bot = SEOPublisherBot()
    result = bot.execute(file_path=args.file, platform=args.platform, title=args.title)
    print(f"Report: {result['file']}")
    print(f"Status: {result['status']}")
    print(f"Published path: {result['published_path']}")
