import requests

# Get posts
url = "http://localhost:8000/wp-json/wp/v2/posts"
response = requests.get(url)

if response.status_code == 200:
    data = response.json()
    print(data)
else:
    print("Error:", response.status_code)

# Example: prepare to post (requires JWT plugin)
data_post = {
    "title": "AI Market Prediction",
    "content": "Generated by Wheellsverse AI",
    "status": "publish"
}
# Posting requires authentication, see JWT plugin setup
