#!/usr/bin/env python3
"""
bots/specialized/71_crypto_content_creator/bot.py
Generates SEO-optimized blog posts and social content on cryptocurrency topics.
Revenue goal: Drive Coinbase signups and crypto-related Amazon purchases.
"""
import os
import sys
import random
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot

COINBASE_URL  = os.getenv("AFFILIATE_COINBASE_URL",  "https://coinbase.com/join/IRZL3QBqT2Fa7117979C7RLARc7WFdWBH1")
ROBINHOOD_URL = os.getenv("AFFILIATE_ROBINHOOD_URL", "https://join.robinhood.com/IRhjrdSej2Ms7117979PpUNgqcMUkCW7g1")
AMAZON_TAG    = os.getenv("AFFILIATE_AMAZON_TAG",    "wheellsverse-20")

CRYPTO_TOPICS = [
    "Bitcoin vs Ethereum: which crypto is right for you in 2025?",
    "How to start investing in crypto with $50 or less",
    "Top 5 crypto platforms with the lowest fees compared",
    "How to earn passive income with crypto staking in 2025",
    "DeFi explained: earn interest on crypto without a bank",
    "Crypto wallets explained: hot vs cold storage — which is safer?",
    "Top altcoins to watch in 2025 beyond Bitcoin and Ethereum",
    "Is crypto still worth investing in? An honest 2025 review",
    "How to dollar-cost average into Bitcoin — a beginner's guide",
    "NFTs vs crypto: where should you put your money in 2025?",
    "Crypto tax basics every investor needs to know",
    "How blockchain technology is changing everyday finance",
]


class CryptoContentCreatorBot(BaseBot):
    """Generates authoritative crypto content that educates readers and drives affiliate conversions."""

    def __init__(self):
        super().__init__("71_crypto_content_creator", "specialized")

    def run(self, topic: str = None, content_type: str = "blog_post", **kwargs):
        cfg = self.config
        topic = topic or cfg.get("default_topic") or random.choice(CRYPTO_TOPICS)
        content_type = content_type or cfg.get("content_type", "blog_post")
        self.logger.info(f"Running {self.name}: {topic}")

        system_str = (
            "You are a professional cryptocurrency educator and content strategist. "
            "You write authoritative, accurate, and engaging articles that build reader trust. "
            "Your content explains complex crypto concepts in plain English, includes real data "
            "and examples, and naturally weaves in affiliate opportunities without being pushy. "
            "You always prioritize reader value — your goal is to be the most helpful crypto "
            "resource they've ever found."
        )

        prompt = f"""Write a comprehensive, SEO-optimized crypto blog post on:

TOPIC: "{topic}"

Structure your article as follows:

## Article Requirements
- **Length:** 900-1200 words
- **Tone:** Knowledgeable but approachable — like a smart friend explaining crypto
- **SEO:** Use the topic as the H1 headline; include it naturally in the intro and 1-2 subheadings

## Required Sections

**1. Compelling H1 Headline** (keyword-rich, value-focused)

**2. Hook Intro** (2-3 sentences: state the problem or opportunity, why it matters NOW in 2025)

**3. Main Content Body** (3-4 H2 sections with):
   - Specific data, examples, or comparisons
   - Practical, actionable steps readers can take
   - Honest pros and cons where relevant

**4. Affiliate Integration** (natural, value-adding mentions):
   - [Coinbase]({COINBASE_URL}): When discussing where to buy/trade crypto — mention the sign-up bonus
   - [Robinhood]({ROBINHOOD_URL}): When discussing stock + crypto investing together
   - [Crypto books on Amazon](https://www.amazon.com/s?k=cryptocurrency+investing+beginners&tag={AMAZON_TAG}): When recommending learning resources

**5. Key Takeaways** (3-5 bullet points summarizing the main points)

**6. Strong CTA** (direct readers to the most relevant next step)

Format as clean Markdown. Make it genuinely helpful — readers should bookmark it."""

        result = self.ai(
            prompt, system=system_str,
            model=os.getenv("OPENAI_MODEL", "gpt-4o"),
            max_tokens=2500
        )

        from datetime import datetime as _dt
        ts = _dt.now().strftime("%Y%m%d_%H%M%S")
        safe_topic = "".join(c if c.isalnum() else "_" for c in topic[:40])

        output = f"""# {topic}
*Generated: {_dt.now().strftime('%Y-%m-%d %H:%M')} | WheellsVerse Crypto Content*

---

{result}

---
*Generated by WheellsVerse Crypto Content Creator Bot — {self.name}*
"""
        path = self.save_output(output, f"crypto_{safe_topic}_{ts}.md", ext="md")
        self.logger.info(f"Saved: {path}")
        return {"file": str(path), "bot": self.name}


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Crypto Content Creator Bot")
    parser.add_argument("--topic", type=str, default=None, help="Specific crypto topic to cover")
    parser.add_argument("--type",  type=str, default="blog_post", choices=["blog_post", "social_post", "newsletter"])
    args = parser.parse_args()
    bot = CryptoContentCreatorBot()
    result = bot.execute(topic=args.topic, content_type=args.type)
    print(f"\n✅ Output: {result['file']}")
