#!/usr/bin/env python3
"""
Bot #5 — Funnel Builder
Category: Marketing
Purpose: Build complete marketing funnels with copy for each stage.
         Awareness → Interest → Desire → Action → Retention
Inputs:  product, price_point, audience, funnel_type
Outputs: Complete funnel document with copy for every stage
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot  # noqa: E402


class FunnelBuilderBot(BaseBot):

    def __init__(self):
        super().__init__("05_funnel_builder", "marketing")

    def run(self, product: str = None, price_point: str = None,
            audience: str = None, funnel_type: str = None,
            brand_name: str = None, **kwargs):

        cfg = self.config
        product = product or cfg.get("product", "WheellsVerse AI Platform")
        price_point = price_point or cfg.get("price_point", "$97/month")
        audience = audience or cfg.get("audience", "entrepreneurs and creators")
        funnel_type = funnel_type or cfg.get("funnel_type", "lead_generation")
        brand_name = brand_name or cfg.get("brand_name", "WheellsVerse")

        self.logger.info(f"Building {funnel_type} funnel for: {product}")

        funnel_types = {
            "lead_generation": "Free lead magnet → Email sequence → Paid offer",
            "product_launch": "Anticipation → Pre-launch → Launch → Close",
            "webinar": "Registration → Pre-webinar emails → Live → Replay → Offer",
            "tripwire": "Free → $7-27 offer → Core offer → Upsell/Downsell",
            "high_ticket": "Free content → Application → Discovery call → Proposal",
            "membership": "Free trial → Onboarding → Monthly value → Renewal",
            "ecommerce": "Traffic → Product page → Cart → Checkout → Post-purchase"
        }

        system = (
            "You are a funnel architect who has built 7-figure sales funnels. "
            "You understand consumer psychology, conversion optimization, and "
            "how to move prospects from awareness to loyal customers."
        )

        structure = funnel_types.get(funnel_type, funnel_type)

        prompt = f"""Build a complete {funnel_type.replace("_", " ")} funnel for:

BRAND: {brand_name}
PRODUCT/SERVICE: {product}
PRICE POINT: {price_point}
TARGET AUDIENCE: {audience}
FUNNEL STRUCTURE: {structure}

Build each funnel stage with:

## STAGE 1: AWARENESS (Top of Funnel)
- Traffic source strategy (organic + paid)
- Hook/angle for cold audience
- Content/ad copy for first touchpoint

## STAGE 2: INTEREST (Opt-in / Lead Capture)
- Lead magnet idea + title
- Opt-in page headline
- Opt-in page subheadline  
- Bullet points (5 benefits)
- Button CTA copy

## STAGE 3: DESIRE (Nurture / Sales Page)
- Email subject lines for 3 nurture emails
- Sales page headline (power headline)
- Problem-Agitate-Solution section
- Benefits list (7 key benefits)
- Social proof section template
- Pricing section copy
- Guarantee copy

## STAGE 4: ACTION (Checkout / Close)
- Order page headline
- Urgency/scarcity copy
- Order bump offer (if applicable)
- Payment button copy
- Thank you page message

## STAGE 5: RETENTION (Post-Purchase / Upsell)
- Welcome email copy
- Onboarding sequence outline
- Upsell offer description + copy
- Referral program copy

## CONVERSION BENCHMARKS
Expected conversion rates at each stage (industry standards)

## TECH STACK RECOMMENDATION
Tools to build this funnel (ClickFunnels, Kajabi, etc.)"""

        funnel = self.ai(prompt, system=system, max_tokens=3500)

        output = f"""# Marketing Funnel Blueprint
**Brand:** {brand_name}
**Product:** {product}
**Price Point:** {price_point}
**Audience:** {audience}
**Funnel Type:** {funnel_type}
**Generated:** {self._now()}

---

{funnel}

---
*Generated by WheellsVerse Funnel Builder Bot*
"""
        safe = funnel_type.replace(" ", "_")
        path = self.save_output(output, f"funnel_{safe}.md", ext="md")
        self.logger.info(f"Funnel blueprint saved → {path}")
        return {"file": str(path), "funnel_type": funnel_type, "product": product}

    def _now(self):
        from datetime import datetime
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Funnel Builder Bot")
    parser.add_argument("--product", type=str, default=None)
    parser.add_argument("--price", type=str, default="$97/month")
    parser.add_argument("--audience", type=str, default=None)
    parser.add_argument("--type", type=str, default="lead_generation")
    parser.add_argument("--brand", type=str, default=None)
    args = parser.parse_args()
    bot = FunnelBuilderBot()
    result = bot.execute(product=args.product, price_point=args.price,
                         audience=args.audience, funnel_type=args.type,
                         brand_name=args.brand)
    print(f"\n✅ Funnel: {result['file']}")
