#!/usr/bin/env python3
"""
Bot #37 — Social Media Auto Post Calendar
Category: Social Media
Purpose: Generate a complete, ready-to-post social media content calendar with
         posts for multiple platforms, optimized for engagement and growth.
"""
import os
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot  # noqa: E402


class AutoPostBot(BaseBot):

    def __init__(self):
        super().__init__("37_auto_post", "social_media")

    def run(self, niche: str = None, platforms: str = None,
            num_days: int = None, posting_frequency: str = None, **kwargs):

        cfg = self.config
        niche = niche or cfg.get("niche", "AI automation and entrepreneurship")
        platforms = platforms or cfg.get("platforms", "twitter,linkedin,instagram")
        num_days = num_days or cfg.get("num_days", 14)
        posting_frequency = posting_frequency or cfg.get("posting_frequency", "1x daily per platform")

        platform_list = [p.strip() for p in platforms.split(",")]
        self.logger.info(f"Generating {num_days}-day content calendar for {niche}")

        content_mix = {
            "twitter": "Threads, single tweets, polls, replies to trending topics",
            "linkedin": "Long-form posts, carousels (listed as bullet points), professional insights",
            "instagram": "Reels concepts, carousels, single image posts, Stories",
            "tiktok": "60-90 second video scripts, trending audio hooks, educational series",
        }

        mix_desc = " | ".join([f"{p.upper()}: {content_mix.get(p, 'mixed content')}" for p in platform_list])

        # Pre-compute platform block to avoid nested triple-quoted f-strings (Python 3.11)
        platform_block = "".join(
            f"**{p.upper()}:**\n"
            "Post type: [Type]\n"
            "Caption/Copy:\n"
            "```\n"
            "[Exact post text - platform-optimized]\n"
            "```\n"
            "Hashtags: [Platform-appropriate hashtags]\n"
            "Best time to post: [Time + timezone note]\n"
            "Visual note: [What image/graphic would work]\n"
            "---\n"
            for p in platform_list
        )

        system = (
            "You are a social media strategist and content creator who has grown "
            "multiple accounts to 10K-100K+ followers. You know that consistent, "
            "high-quality content beats viral attempts. You create calendars that "
            "mix content types (education, entertainment, inspiration, promotion) "
            "in the right ratio -- typically 80% value, 20% promotional. "
            "Every post has a clear purpose and drives toward a business goal."
        )

        prompt = f"""Create a {num_days}-day social media content calendar for:

NICHE: {niche}
PLATFORMS: {', '.join(platform_list)}
POSTING: {posting_frequency}
BRAND: WheellsVerse - AI automation tools

Content mix guidance: {mix_desc}

## CONTENT STRATEGY
- **Content pillars** for {niche} (4-5 recurring themes)
- **Target audience:** Who is this content for?
- **Content ratio:** [X% educational : Y% inspirational : Z% promotional]
- **Growth goal:** What this calendar is designed to achieve

## {num_days}-DAY CONTENT CALENDAR

For each day, provide posts for each platform:

---
### DAY [N] - [Day of Week] - [Theme/Pillar]

{platform_block}
[Repeat for all {num_days} days]

## RECURRING CONTENT SERIES
2-3 recurring series to run weekly (e.g., "Monday Motivation", "Friday Tool Review"):
| Series Name | Day | Format | Hook Template |

## CONTENT BATCH GUIDE
How to create all {num_days} days of content in one 3-hour session:
1. [Step 1]
2. [Step 2]
...

## PERFORMANCE TRACKER
Weekly metrics to track for this calendar:
| Metric | Baseline | Week 2 Target | Month-End Target |"""

        result = self.ai(prompt, system=system,
                         model=os.getenv("OPENAI_MODEL", "gpt-4o"),
                         max_tokens=3500)

        from datetime import datetime as _dt
        ts = _dt.now().strftime("%Y%m%d_%H%M%S")
        safe_niche = self.slugify(niche, 20)

        output = f"""# {num_days}-Day Content Calendar: {niche}
**Platforms:** {platforms}
**Frequency:** {posting_frequency}
**Generated:** {_dt.now().strftime('%Y-%m-%d %H:%M')}

---

{result}

---
*Generated by WheellsVerse Auto Post Bot*
"""
        path = self.save_output(output, f"calendar_{safe_niche}_{ts}.md", ext="md")
        self.logger.info(f"Content calendar saved -> {path}")
        return {"file": str(path), "niche": niche, "days": num_days, "platforms": platform_list}


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Social Media Auto Post Calendar")
    parser.add_argument("--niche", type=str, default=None)
    parser.add_argument("--platforms", type=str, default="twitter,linkedin,instagram")
    parser.add_argument("--days", type=int, default=14)
    parser.add_argument("--frequency", type=str, default="1x daily per platform")
    args = parser.parse_args()
    bot = AutoPostBot()
    result = bot.execute(niche=args.niche, platforms=args.platforms,
                         num_days=args.days, posting_frequency=args.frequency)
    print(f"\n✅ Content Calendar: {result['file']}")
