#!/usr/bin/env python3
"""
Bot #3 — Email Campaign Generator
Category: Marketing
Purpose: Build complete multi-email sequences (welcome, nurture, sales, re-engagement).
Inputs:  campaign_type, product/service, audience, num_emails, brand_name
Outputs: Complete email sequence as Markdown + JSON
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot  # noqa: E402


class EmailCampaignBot(BaseBot):

    def __init__(self):
        super().__init__("03_email_campaign", "marketing")

    def run(self, campaign_type: str = None, product: str = None,
            audience: str = None, num_emails: int = None,
            brand_name: str = None, **kwargs):

        cfg = self.config
        campaign_type = campaign_type or cfg.get("campaign_type", "welcome_series")
        product = product or cfg.get("product", "AI automation platform")
        audience = audience or cfg.get("audience", "entrepreneurs and small business owners")
        num_emails = num_emails or cfg.get("num_emails", 5)
        brand_name = brand_name or cfg.get("brand_name", "WheellsVerse")

        self.logger.info(f"Building {campaign_type} campaign ({num_emails} emails) for {brand_name}")

        campaign_types = {
            "welcome_series": "a welcome email series for new subscribers",
            "sales_funnel": "a sales funnel sequence to convert leads to buyers",
            "nurture": "a lead nurturing sequence to build trust over time",
            "re_engagement": "a re-engagement campaign for inactive subscribers",
            "launch": "a product launch email sequence",
            "onboarding": "a customer onboarding email sequence",
            "abandoned_cart": "an abandoned cart recovery sequence"
        }
        ct_label = campaign_types.get(campaign_type, campaign_type)

        system = (
            "You are a world-class email marketer who has generated millions in revenue "
            "through email sequences. Write compelling, personalized emails with strong "
            "subject lines, preview text, and CTAs."
        )

        prompt = f"""Create {ct_label} for the following:

BRAND: {brand_name}
PRODUCT/SERVICE: {product}
TARGET AUDIENCE: {audience}
NUMBER OF EMAILS: {num_emails}

For EACH email provide:
1. EMAIL NUMBER & DAY SENT (e.g., Email 1 — Day 0)
2. SUBJECT LINE (A/B test: provide 2 options)
3. PREVIEW TEXT (under 100 chars)
4. FROM NAME suggestion
5. EMAIL BODY (full HTML-friendly copy with personalization tokens like {{first_name}})
6. CALL-TO-ACTION (button text + link placeholder)
7. UNSUBSCRIBE NOTE

Make each email feel personal, valuable, and different from the previous one.
Use storytelling, social proof, urgency where appropriate.
Integrate personalized affiliate links based on audience segmentation to improve conversion rates.
Format clearly with === separators between emails."""

        campaign = self.ai(prompt, system=system, max_tokens=3500)

        output = f"""# Email Campaign: {campaign_type.replace("_", " ").title()}
**Brand:** {brand_name}
**Product:** {product}
**Audience:** {audience}
**Emails:** {num_emails}
**Generated:** {self._now()}

---

{campaign}

---
*Generated by WheellsVerse Email Campaign Bot*
"""
        safe_name = campaign_type.replace(" ", "_")
        path = self.save_output(output, f"campaign_{safe_name}.md", ext="md")
        self.logger.info(f"Campaign saved → {path}")
        return {"file": str(path), "campaign_type": campaign_type, "num_emails": num_emails}

    def _now(self):
        from datetime import datetime
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Email Campaign Generator")
    parser.add_argument("--type", type=str, default="welcome_series")
    parser.add_argument("--product", type=str, default=None)
    parser.add_argument("--audience", type=str, default=None)
    parser.add_argument("--emails", type=int, default=5)
    parser.add_argument("--brand", type=str, default=None)
    args = parser.parse_args()
    bot = EmailCampaignBot()
    result = bot.execute(campaign_type=args.type, product=args.product,
                         audience=args.audience, num_emails=args.emails,
                         brand_name=args.brand)
    print(f"\n✅ Campaign: {result['file']}")
