#!/usr/bin/env python3
"""
core/heygen.py
─────────────────────────────────────────────────────────────────────────────
HeyGen AI Avatar Engine — the face of WheellsVerse / NarAI.

Creates talking-head videos in two formats:
  • Landscape 16:9 (1280×720) — YouTube, Facebook
  • Vertical 9:16  (720×1280) — YouTube Shorts, TikTok, Instagram Reels

Full pipeline per video:
  1. Select avatar + voice (from .env or passed in)
  2. Submit video generation job
  3. Poll until ready (HeyGen renders asynchronously)
  4. Download MP4 to outputs/videos/
  5. Return local path for downstream publishing

.env keys:
  HEYGEN_API_KEY      — from app.heygen.com → API Settings
  HEYGEN_AVATAR_ID    — avatar ID (get from list_avatars())
  HEYGEN_VOICE_ID     — HeyGen voice ID (or use ElevenLabs audio instead)

ElevenLabs integration:
  When ELEVENLABS_API_KEY is set, voice is generated by ElevenLabs first,
  then uploaded to HeyGen as custom audio for the avatar. This gives the
  consistent NarAI voice on top of HeyGen's avatar lip-sync.
─────────────────────────────────────────────────────────────────────────────
"""

import logging
import os
import time
from pathlib import Path
from typing import Dict, List, Optional

import requests
from dotenv import load_dotenv

ROOT = Path(__file__).parent.parent
load_dotenv(ROOT / ".env")

VIDEO_DIR = ROOT / "outputs" / "videos"
VIDEO_DIR.mkdir(parents=True, exist_ok=True)

logger = logging.getLogger("heygen")

HEYGEN_API = "https://api.heygen.com"
API_KEY = os.getenv("HEYGEN_API_KEY", "")
AVATAR_ID = os.getenv("HEYGEN_AVATAR_ID", "")
VOICE_ID = os.getenv("HEYGEN_VOICE_ID", "")
POLL_SLEEP = 15    # seconds between status polls
MAX_WAIT = 600   # 10 minutes max render time


def _headers() -> dict:
    return {"X-Api-Key": API_KEY, "Content-Type": "application/json"}


def is_configured() -> bool:
    return bool(API_KEY and AVATAR_ID)


# ─── Avatar & Voice Discovery ────────────────────────────────────────────────

def list_avatars() -> List[Dict]:
    """Return all available avatars in the HeyGen account."""
    if not API_KEY:
        return []
    try:
        resp = requests.get(f"{HEYGEN_API}/v2/avatars",
                            headers=_headers(), timeout=20)
        if resp.status_code == 200:
            avatars = resp.json().get("data", {}).get("avatars", [])
            logger.info(f"[HeyGen] {len(avatars)} avatars available")
            return avatars
        logger.warning(f"[HeyGen] list_avatars: {resp.status_code} {resp.text[:200]}")
        return []
    except Exception as e:
        logger.error(f"[HeyGen] list_avatars failed: {e}")
        return []


def list_voices() -> List[Dict]:
    """Return all available voices for HeyGen text-to-speech."""
    if not API_KEY:
        return []
    try:
        resp = requests.get(f"{HEYGEN_API}/v2/voices",
                            headers=_headers(), timeout=20)
        if resp.status_code == 200:
            voices = resp.json().get("data", {}).get("voices", [])
            logger.info(f"[HeyGen] {len(voices)} voices available")
            return voices
        return []
    except Exception as e:
        logger.error(f"[HeyGen] list_voices failed: {e}")
        return []


# ─── Video Generation ─────────────────────────────────────────────────────────

def generate_video(
    script: str,
    title: str = "",
    format: str = "shorts",          # "shorts" (9:16) or "landscape" (16:9)
    avatar_id: str = None,
    voice_id: str = None,
    use_elevenlabs: bool = True,      # prefer ElevenLabs voice over HeyGen TTS
    background_color: str = "#080b11",
    caption: bool = True,
) -> Dict:
    """
    Submit a video generation job to HeyGen.
    Returns {"video_id": "...", "status": "pending"}  or {"error": "..."}
    """
    if not is_configured():
        return {"error": "HEYGEN_API_KEY or HEYGEN_AVATAR_ID not set in .env"}

    aid = avatar_id or AVATAR_ID
    vid = voice_id or VOICE_ID
    script = script.strip()[:1500]   # HeyGen per-segment limit

    # Dimensions
    if format == "shorts":
        width, height = 720, 1280
    else:
        width, height = 1280, 720

    # Build voice config — ElevenLabs audio takes priority
    audio_url = None
    if use_elevenlabs:
        audio_url = _generate_elevenlabs_audio_url(script, title)

    if audio_url:
        voice_config = {
            "type": "audio",
            "audio_url": audio_url,
        }
    elif vid:
        voice_config = {
            "type": "text",
            "input_text": script,
            "voice_id": vid,
        }
    else:
        voice_config = {
            "type": "text",
            "input_text": script,
            "voice_id": "en-US-BrianNeural",  # HeyGen default
        }

    payload = {
        "video_inputs": [{
            "character": {
                "type": "avatar",
                "avatar_id": aid,
                "avatar_style": "normal",
            },
            "voice": voice_config,
            "background": {
                "type": "color",
                "value": background_color,
            },
        }],
        "dimension": {"width": width, "height": height},
        "caption": caption,
        "title": title[:100] if title else "WheellsVerse Short",
    }

    try:
        resp = requests.post(
            f"{HEYGEN_API}/v2/video/generate",
            json=payload,
            headers=_headers(),
            timeout=30,
        )
        data = resp.json()

        if resp.status_code == 200 and data.get("error") is None:
            video_id = data.get("data", {}).get("video_id", "")
            logger.info(f"[HeyGen] Video submitted: {video_id} ({format} {width}×{height})")
            return {"video_id": video_id, "status": "pending",
                    "format": format, "title": title}

        err = data.get("error") or {}
        msg = err.get("message", str(data)) if isinstance(err, dict) else str(err)
        logger.error(f"[HeyGen] generate_video error: {msg}")
        return {"error": msg}

    except Exception as e:
        logger.error(f"[HeyGen] generate_video failed: {e}")
        return {"error": str(e)}


def poll_until_ready(video_id: str, max_wait: int = MAX_WAIT) -> Dict:
    """
    Poll HeyGen until the video is completed or failed.
    Returns {"status": "completed", "video_url": "...", "thumbnail_url": "...", "download_path": Path}
    """
    start = time.time()
    attempt = 0

    while time.time() - start < max_wait:
        attempt += 1
        try:
            resp = requests.get(
                f"{HEYGEN_API}/v1/video_status.get",
                params={"video_id": video_id},
                headers=_headers(),
                timeout=20,
            )
            data = resp.json().get("data", {})
            status = data.get("status", "")

            logger.info(f"[HeyGen] Poll #{attempt}: {video_id} → {status}")

            if status == "completed":
                video_url = data.get("video_url", "")
                thumbnail_url = data.get("thumbnail_url", "")
                # Download the video locally
                local_path = _download_video(video_url, video_id)
                return {
                    "status": "completed",
                    "video_url": video_url,
                    "thumbnail_url": thumbnail_url,
                    "download_path": local_path,
                }

            if status in ("failed", "error"):
                err = data.get("error", "unknown error")
                logger.error(f"[HeyGen] Video failed: {err}")
                return {"status": "failed", "error": err}

        except Exception as e:
            logger.warning(f"[HeyGen] Poll error: {e}")

        time.sleep(POLL_SLEEP)

    return {"status": "timeout", "error": f"Video not ready after {max_wait}s"}


def create_video_and_wait(
    script: str,
    title: str = "",
    format: str = "shorts",
    **kwargs,
) -> Dict:
    """
    One-call convenience: submit + poll until done.
    Returns the completed result dict with local download_path.
    """
    submit = generate_video(script, title=title, format=format, **kwargs)
    if "error" in submit:
        return submit

    video_id = submit["video_id"]
    result = poll_until_ready(video_id)
    result["video_id"] = video_id
    result["title"] = title
    result["format"] = format
    return result


# ─── Account Info ─────────────────────────────────────────────────────────────

def get_remaining_credits() -> Optional[int]:
    """Return remaining video credits in the HeyGen account."""
    if not API_KEY:
        return None
    try:
        resp = requests.get(f"{HEYGEN_API}/v2/user/remaining_quota",
                            headers=_headers(), timeout=10)
        if resp.status_code == 200:
            return resp.json().get("data", {}).get("remaining_quota")
        return None
    except Exception:
        return None


def get_video_list(limit: int = 20) -> List[Dict]:
    """Return recent videos from the HeyGen account."""
    if not API_KEY:
        return []
    try:
        resp = requests.get(
            f"{HEYGEN_API}/v1/video.list",
            params={"limit": limit},
            headers=_headers(),
            timeout=15,
        )
        if resp.status_code == 200:
            return resp.json().get("data", {}).get("videos", [])
        return []
    except Exception as e:
        logger.error(f"[HeyGen] get_video_list failed: {e}")
        return []


# ─── Internal helpers ─────────────────────────────────────────────────────────

def _generate_elevenlabs_audio_url(script: str, title: str = "") -> Optional[str]:
    """
    Generate audio via ElevenLabs and return a publicly accessible URL
    by uploading to a temp hosting service, or fall back to None.
    HeyGen requires a public URL for custom audio — we use the Railway
    server to serve the file from /outputs/audio/.
    """
    try:
        from core import elevenlabs as el
        if not el.is_configured():
            return None

        safe = "".join(c if c.isalnum() else "_" for c in title[:30])
        filename = f"hg_audio_{safe}_{int(time.time())}.mp3"
        audio_path = el.speak(script, filename=filename)

        if not audio_path or not audio_path.exists():
            return None

        # Build Railway public URL so HeyGen can fetch the audio
        base_url = os.getenv("RAILWAY_PUBLIC_URL",
                             "https://grateful-flexibility-production.up.railway.app")
        rel_path = audio_path.relative_to(ROOT)
        public_url = f"{base_url}/outputs/{rel_path.relative_to(Path('outputs'))}"
        logger.info(f"[HeyGen] ElevenLabs audio ready: {public_url}")
        return str(public_url)

    except Exception as e:
        logger.warning(f"[HeyGen] ElevenLabs audio generation failed: {e}")
        return None


def _download_video(url: str, video_id: str) -> Optional[Path]:
    """Download video from HeyGen CDN to local outputs/videos/."""
    if not url:
        return None
    try:
        resp = requests.get(url, timeout=120, stream=True)
        if resp.status_code == 200:
            out_path = VIDEO_DIR / f"{video_id}.mp4"
            with open(out_path, "wb") as f:
                for chunk in resp.iter_content(chunk_size=65536):
                    f.write(chunk)
            size_mb = out_path.stat().st_size / 1_000_000
            logger.info(f"[HeyGen] Downloaded {size_mb:.1f}MB → {out_path}")
            return out_path
        logger.warning(f"[HeyGen] Download failed {resp.status_code}")
        return None
    except Exception as e:
        logger.error(f"[HeyGen] Download error: {e}")
        return None


# ─── Module self-test ─────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("HeyGen Status:")
    print(f"  Configured: {is_configured()}")
    credits = get_remaining_credits()
    print(f"  Remaining credits: {credits}")
    avatars = list_avatars()
    print(f"  Avatars: {len(avatars)}")
    for a in avatars[:3]:
        print(f"    • {a.get('avatar_name')} ({a.get('avatar_id')})")
    voices = list_voices()
    print(f"  Voices: {len(voices)}")
    for v in voices[:3]:
        print(f"    • {v.get('name')} ({v.get('voice_id')}) — {v.get('language')}")
