#!/usr/bin/env python3
"""
bots/specialized/74_passive_income_bot/bot.py
Generates passive income content with embedded affiliate links across multiple formats.
Revenue goal: Drive affiliate conversions through high-quality passive income education.
"""
import os
import sys
import random
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot  # noqa: E402
from core.affiliate import make_utm, AMAZON_TAG  # noqa: E402

_utm = make_utm("74_passive_income_bot")


# OLD: COINBASE_URL = os.getenv("AFFILIATE_COINBASE_URL", "https://app.wheellsverse.com/go/coinbase")
COINBASE_URL = _utm("coinbase")
# OLD: ROBINHOOD_URL = os.getenv("AFFILIATE_WEBULL_URL", "https://app.wheellsverse.com/go/webull")
WEBULL_URL = _utm("webull")

PASSIVE_INCOME_IDEAS = [
    "dividend investing for beginners",
    "crypto staking and yield farming",
    "high-yield savings accounts vs investing",
    "peer-to-peer lending platforms",
    "affiliate marketing for content creators",
    "digital product income streams",
    "REITs and real estate crowdfunding",
    "covered call options for passive income",
    "automated dropshipping businesses",
    "print-on-demand passive income",
    "YouTube AdSense revenue strategies",
    "creating and selling online courses",
]

CONTENT_FORMATS = {
    "guide": "a comprehensive beginner's guide",
    "listicle": "a ranked list article with explanations",
    "case_study": "a realistic case study with hypothetical numbers",
    "comparison": "a side-by-side comparison of strategies",
    "action_plan": "a 30-day action plan",
}


class PassiveIncomeBotBot(BaseBot):
    """Generates diverse passive income content formats to maximize affiliate conversions."""

    def __init__(self):
        super().__init__("74_passive_income_bot", "specialized")

    def run(self, topic: str = None, format_type: str = "guide", **kwargs):
        cfg = self.config
        topic = topic or cfg.get("default_topic") or random.choice(PASSIVE_INCOME_IDEAS)
        format_type = format_type or cfg.get("format_type", "guide")
        format_label = CONTENT_FORMATS.get(format_type, "a comprehensive guide")
        self.logger.info(f"Running {self.name}: {topic} [{format_type}]")

        system_str = (
            "You are a financial independence writer and passive income expert. "
            "You create content that is specific, realistic, and actionable. "
            "You don't overpromise — you show exactly how much work is involved and "
            "what realistic returns look like. Your content builds long-term trust "
            "with readers who are serious about building financial freedom."
        )

        prompt = f"""Create {format_label} on passive income topic: "{topic}"

## Affiliate Links to Integrate Naturally
- [Webull — free stocks investing]({WEBULL_URL}): Use for stock/dividend-related sections
- [Coinbase — crypto investing]({COINBASE_URL}): Use for crypto-related sections
# OLD: - [Amazon — passive income books](https://www.amazon.com/s?k={topic.replace(' ', '+')}&tag={AMAZON_TAG}): Recommend at the end
- [Amazon — passive income books]({_utm('amazon_passive_topic')}): Recommend at the end

## Content Requirements
- **Length:** 800-1100 words
- **Format:** {format_label.title()}
- **Tone:** Expert but relatable — like talking to a financially savvy friend

## Required Elements
1. **Strong Opening** — hook with a specific stat or scenario about "{topic}"
2. **Core Content** — detailed, specific information on "{topic}" with:
   - Real numbers and realistic timelines
   - Step-by-step process where applicable
   - Pros and cons honestly stated
   - Tools and platforms that actually help
3. **Affiliate Integration** — weave in the links above where they naturally fit
4. **Common Mistakes** — 2-3 pitfalls to avoid
5. **Bottom Line** — honest verdict and recommended starting point
6. **CTA** — specific next action to take today

Format as clean Markdown with scannable headers."""

        result = self.ai(
            prompt, system=system_str,
            model=os.getenv("OPENAI_MODEL", "gpt-4o"),
            max_tokens=2500
        )

        from datetime import datetime as _dt
        ts = _dt.now().strftime("%Y%m%d_%H%M%S")
        safe_topic = self.slugify(topic, 40)

        output = f"""# Passive Income: {topic.title()}
*Format: {format_label.title()} | Generated: {_dt.now().strftime('%Y-%m-%d %H:%M')}*

---

{result}

---
*Generated by WheellsVerse Passive Income Bot — {self.name}*
"""
        path = self.save_output(output, f"passive_{format_type}_{safe_topic}_{ts}.md", ext="md")
        self.logger.info(f"Saved: {path}")
        return {"file": str(path), "format": format_type, "bot": self.name}


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Passive Income Bot")
    parser.add_argument("--topic", type=str, default=None, help="Passive income topic")
    parser.add_argument("--format", type=str, default="guide",
                        choices=["guide", "listicle", "case_study", "comparison", "action_plan"])
    args = parser.parse_args()
    bot = PassiveIncomeBotBot()
    result = bot.execute(topic=args.topic, format_type=args.format)
    print(f"\n✅ Output: {result['file']}")
