#!/usr/bin/env python3
"""
bots/marketing/75_affiliate_sales_booster/bot.py
Generates high-converting affiliate marketing content and campaign strategies.
Revenue goal: Maximize affiliate conversions through targeted, trust-building content.
"""
import os
import sys
import random
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot  # noqa: E402

# OLD constants block read AFFILIATE_<X>_URL from .env with /go/{partner}
# OLD fallbacks. Per affiliate_swap_pass2_2026_06_02 every CTA now
# OLD routes to the owned digital product / blog with UTM tagging.
_BOT = "75_affiliate_sales_booster"
_CAMP = "affiliate_swap_pass2_2026_06_02"
_DIGITAL = "https://stan.store/Wheellsverse"
_BLOG = "https://wheellsverse.com/blog/"


def _utm(content: str, medium: str = "content", base: str = _DIGITAL) -> str:
    return f"{base}?utm_source={_BOT}&utm_medium={medium}&utm_campaign={_CAMP}&utm_content={content}"


# OLD: COINBASE_URL = os.getenv("AFFILIATE_COINBASE_URL", "https://app.wheellsverse.com/go/coinbase")
COINBASE_URL = _utm("coinbase")
# OLD: ROBINHOOD_URL = os.getenv("AFFILIATE_WEBULL_URL", "https://app.wheellsverse.com/go/webull")
WEBULL_URL = _utm("webull")
AMAZON_TAG = os.getenv("AFFILIATE_AMAZON_TAG", "wheellsverse-20")

AFFILIATE_ANGLES = [
    "Why I switched to Robinhood and what happened to my portfolio",
    "Coinbase vs other crypto apps: my honest review after 1 year",
    "How to make your first $100 in affiliate commissions this week",
    "The affiliate marketing funnel that earns money on autopilot",
    "Best affiliate programs for personal finance bloggers in 2025",
    "How to promote financial products ethically and still earn well",
    "Email list affiliate marketing: how to earn from every newsletter",
    "The content-to-conversion strategy that 10x my affiliate income",
    "Why honest reviews convert better than promotional content",
    "How to build affiliate authority in the investing niche",
]


class AffiliateSalesBoosterBot(BaseBot):
    """Creates high-converting affiliate content and campaign strategies focused on financial products."""

    def __init__(self):
        super().__init__("75_affiliate_sales_booster", "marketing")

    def run(self, topic: str = None, campaign_type: str = "content", **kwargs):
        cfg = self.config
        topic = topic or cfg.get("default_topic") or random.choice(AFFILIATE_ANGLES)
        campaign_type = campaign_type or cfg.get("campaign_type", "content")
        self.logger.info(f"Running {self.name}: {topic}")

        system_str = (
            "You are an affiliate marketing strategist with deep expertise in financial products. "
            "You know that trust converts — readers who trust your recommendations click and buy. "
            "You create content that is honest, detailed, and genuinely helpful. "
            "You never use cheap tactics like fake urgency or misleading claims. "
            "Your affiliate content adds real value and positions products in the context "
            "of how they solve specific reader problems."
        )

        prompt = f"""Create a high-converting affiliate marketing piece on: "{topic}"

## Our Affiliate Products to Feature
- **Robinhood** ({WEBULL_URL}) — Commission-free stock + crypto investing, free stock for new users
- **Coinbase** ({COINBASE_URL}) — Top crypto exchange, get $10 in BTC when you sign up
- **Amazon** (tag: {AMAZON_TAG}) — Relevant books and tools for financial education

## Content Brief

**Campaign Type:** {campaign_type}
**Primary Goal:** Drive affiliate clicks and signups through trust-based content

## Deliverables

**1. Main Content Piece** (700-900 words):
   - Engaging, honest take on the topic
   - Natural product mentions tied to reader benefits
   - Specific features that matter to the reader (not generic praise)
   - Real comparison or context (vs alternatives)
   - Transparent affiliate disclosure where appropriate

**2. Email Subject Lines** (3 A/B test options for promoting this content)

**3. Social Media Hook** (1 punchy opener for Twitter/X or LinkedIn that drives clicks)

**4. CTA Optimization** (2 CTA variants — one soft, one direct — with button text suggestions)

**5. SEO Keywords** (5 relevant long-tail keywords this piece should target)

Make the content genuinely useful. The best affiliate content earns trust first, clicks second."""

        result = self.ai(
            prompt, system=system_str,
            model=os.getenv("OPENAI_MODEL", "gpt-4o"),
            max_tokens=2500
        )

        from datetime import datetime as _dt
        ts = _dt.now().strftime("%Y%m%d_%H%M%S")
        safe_topic = "".join(c if c.isalnum() else "_" for c in topic[:40])

        output = f"""# Affiliate Campaign: {topic}
*Campaign Type: {campaign_type} | Generated: {_dt.now().strftime('%Y-%m-%d %H:%M')}*

---

{result}

---
*Generated by WheellsVerse Affiliate Sales Booster — {self.name}*
"""
        path = self.save_output(output, f"affiliate_{safe_topic}_{ts}.md", ext="md")
        self.logger.info(f"Saved: {path}")
        return {"file": str(path), "topic": topic, "campaign_type": campaign_type, "bot": self.name}


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Affiliate Sales Booster Bot")
    parser.add_argument("--topic", type=str, default=None, help="Affiliate campaign angle/topic")
    parser.add_argument("--campaign", type=str, default="content",
                        choices=["content", "email", "social", "review", "comparison"])
    args = parser.parse_args()
    bot = AffiliateSalesBoosterBot()
    result = bot.execute(topic=args.topic, campaign_type=args.campaign)
    print(f"\n✅ Output: {result['file']}")
