#!/usr/bin/env python3
"""
bots/marketing/73_passive_income_strategy/bot.py
Develops passive income strategy content with affiliate marketing integration.
Revenue goal: Drive recurring affiliate revenue through high-value strategy content.
"""
import os
import sys
import random
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot  # noqa: E402

COINBASE_URL = os.getenv("AFFILIATE_COINBASE_URL", "https://coinbase.com/join/IRZL3QBqT2Fa7117979C7RLARc7WFdWBH1")
ROBINHOOD_URL = os.getenv("AFFILIATE_ROBINHOOD_URL", "https://join.robinhood.com/IRhjrdSej2Ms7117979PpUNgqcMUkCW7g1")
AMAZON_TAG = os.getenv("AFFILIATE_AMAZON_TAG", "wheellsverse-20")

PASSIVE_INCOME_TOPICS = [
    "7 passive income streams anyone can start with $0 in 2025",
    "How to make $500/month in passive income: a realistic roadmap",
    "The best passive income apps that actually pay in 2025",
    "How to earn passive income from dividend stocks — a beginner's guide",
    "Crypto staking explained: earn passive income without trading",
    "How to build a content business that earns while you sleep",
    "5 low-risk passive income ideas for risk-averse investors",
    "How to start affiliate marketing as a side hustle in 2025",
    "Real estate vs stocks: which builds passive income faster?",
    "The passive income mindset: why most people fail and how to succeed",
    "How to earn passive income with digital products and downloads",
    "Automated investing: set it and forget it income strategies",
]


class PassiveIncomeStrategyBot(BaseBot):
    """Creates compelling passive income strategy content that builds authority and drives affiliate conversions."""

    def __init__(self):
        super().__init__("73_passive_income_strategy", "marketing")

    def run(self, topic: str = None, income_target: str = "$500/month", **kwargs):
        cfg = self.config
        topic = topic or cfg.get("default_topic") or random.choice(PASSIVE_INCOME_TOPICS)
        income_target = income_target or cfg.get("income_target", "$500/month")
        self.logger.info(f"Running {self.name}: {topic}")

        system_str = (
            "You are a passive income strategist and personal finance content creator. "
            "You have built multiple passive income streams and document your journey to help others. "
            "Your writing is authentic, practical, and motivating — you give real strategies, "
            "not vague advice. You include specific numbers, timelines, and honest assessments "
            "of what works and what doesn't. You build trust by being transparent about risks."
        )

        prompt = f"""Write a high-value, comprehensive passive income article:

TOPIC: "{topic}"
INCOME TARGET CONTEXT: {income_target}

## Article Requirements
- **Length:** 1000-1300 words
- **Tone:** Authentic, motivating, practical — like advice from someone who actually does this
- **Structure:** Scannable with clear H2/H3 headers, bullet points, and numbered lists

## Required Sections

**1. Compelling Headline** (specific, outcome-focused, includes a number where possible)

**2. Hook** (open with a relatable scenario or surprising stat about passive income)

**3. Why This Works** (the core concept/mechanism behind this income strategy)

**4. Step-by-Step Strategy** (specific, actionable steps — not vague advice):
   - Exact platforms, tools, or methods to use
   - Realistic time investment required
   - Expected income potential at 30/60/90 days
   - Common mistakes and how to avoid them

**5. Tools & Platforms That Make This Easier** (natural affiliate integration):
   - [Robinhood]({ROBINHOOD_URL}): For dividend investing / stock-based passive income
   - [Coinbase]({COINBASE_URL}): For crypto staking / DeFi passive income opportunities
   - [Passive Income Books on Amazon](https://www.amazon.com/s?k=passive+income+strategies+2025&tag={AMAZON_TAG}): For deeper learning

**6. Realistic Expectations** (honest timeline and earnings potential)

**7. Your Next Step** (clear, low-friction CTA)

Be honest about the work required upfront. Passive income is not 'no work' — it's 'front-loaded work.'"""

        result = self.ai(
            prompt, system=system_str,
            model=os.getenv("OPENAI_MODEL", "gpt-4o"),
            max_tokens=2500
        )

        from datetime import datetime as _dt
        ts = _dt.now().strftime("%Y%m%d_%H%M%S")
        safe_topic = "".join(c if c.isalnum() else "_" for c in topic[:40])

        output = f"""# {topic}
*Generated: {_dt.now().strftime('%Y-%m-%d %H:%M')} | WheellsVerse Passive Income Strategy*

---

{result}

---
*Generated by WheellsVerse Passive Income Strategy Bot — {self.name}*
"""
        path = self.save_output(output, f"passive_{safe_topic}_{ts}.md", ext="md")
        self.logger.info(f"Saved: {path}")
        return {"file": str(path), "topic": topic, "bot": self.name}


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Passive Income Strategy Bot")
    parser.add_argument("--topic", type=str, default=None, help="Passive income topic")
    parser.add_argument("--target", type=str, default="$500/month", help="Income target for context")
    args = parser.parse_args()
    bot = PassiveIncomeStrategyBot()
    result = bot.execute(topic=args.topic, income_target=args.target)
    print(f"\n✅ Output: {result['file']}")
