"""infra.brain.learning — heuristic, deterministic learning hooks for the
brain runtime. No ML, no external services. Public surface kept narrow so
the autonomous repair pipeline has exactly one place to import from.
"""
from .repair_memory import (
    # Constants
    CATEGORY_EXECUTOR_TOOL,
    CATEGORY_PLANNER,
    CATEGORY_TELEMETRY,
    CATEGORY_UNKNOWN,
    CATEGORY_VALIDATION,
    DEFAULT_MEMORY_PATH,
    DEFAULT_RISK_PENALTY,
    DEFAULT_THRESHOLD,
    FIX_GUARDRAIL,
    FIX_NULL_SAFETY,
    FIX_PARSING,
    FIX_RETRY,
    FIX_TIMEOUT,
    FIX_UNCLASSIFIED,
    FIX_VALIDATION,
    LOOP_PENALTY,
    LOOP_THRESHOLD,
    LOOP_WINDOW,
    MIN_CASES_FOR_GATE,
    RECENT_FAIL_FLOOR,
    RECENT_PASS_FLOOR,
    RECENT_WINDOW,
    REPUTATION_BONUS,
    REPUTATION_HIGH_RATE,
    REPUTATION_LOW_RATE,
    REPUTATION_MIN_SAMPLES,
    REPUTATION_PENALTY,
    RISK_PROFILES,
    THRESHOLD_LOWER,
    THRESHOLD_RAISE,
    VALID_CATEGORIES,
    VALID_FIX_PATTERNS,
    VALID_RESULTS,
    # Classes
    RepairMemory,
    SafetyScore,
    # Helpers
    classify_fix_pattern,
    compute_failure_signature,
    derive_failure_category,
    normalize_patch,
    patch_signature,
)

__all__ = [
    "RepairMemory",
    "SafetyScore",
    "compute_failure_signature",
    "derive_failure_category",
    "classify_fix_pattern",
    "normalize_patch",
    "patch_signature",
    "DEFAULT_THRESHOLD",
    "MIN_CASES_FOR_GATE",
    "DEFAULT_MEMORY_PATH",
    "VALID_RESULTS",
    "VALID_CATEGORIES",
    "VALID_FIX_PATTERNS",
    "CATEGORY_PLANNER", "CATEGORY_EXECUTOR_TOOL",
    "CATEGORY_TELEMETRY", "CATEGORY_VALIDATION", "CATEGORY_UNKNOWN",
    "FIX_VALIDATION", "FIX_NULL_SAFETY", "FIX_TIMEOUT", "FIX_PARSING",
    "FIX_RETRY", "FIX_GUARDRAIL", "FIX_UNCLASSIFIED",
]
