#!/usr/bin/env python3
"""
Bot #98 — AI Sales Agent
Category: Agent Workforce
Purpose: Generate cold outreach emails, follow-up sequences, and business
         proposals using Claude as the AI backend.
"""

import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot  # noqa: E402


class SalesAgentBot(BaseBot):
    """AI sales agent  outreach, follow-ups, and proposals powered by Claude."""

    def __init__(self):
        super().__init__("98_sales_bot", "agent_workforce")

    def run(self, action: str = "outreach", prospect: str = None,
            context: str = None, industry: str = None, **kwargs):

        prospect = prospect or "a decision-maker at a mid-size SaaS company"
        context = context or "They are looking to automate their content marketing and social media workflows"
        industry = industry or "SaaS / Technology"

        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        ts_display = datetime.now().strftime("%Y-%m-%d %H:%M")

        # ── Outreach ────────────────────────────────────────────────────────
        if action == "outreach":
            self.logger.info(f"Generating cold outreach for: {prospect[:60]}")

            system = (
                "You are a world-class B2B sales copywriter. You write cold emails "
                "that get opened, read, and replied to. Your style: concise, personal, "
                "value-first. You never sound like a template. You lead with the "
                "prospect's problem, not your product. Every email has a clear, low-friction CTA. "
                "You write like a human, not a marketer."
            )

            prompt = f"""Write a cold outreach email campaign for:

PROSPECT: {prospect}
INDUSTRY: {industry}
CONTEXT: {context}
SENDER: WheellsVerse (AI automation platform for businesses)

Create THREE subject line variants (A, B, C) and the email body.

Format:
## Subject Line A
[Subject]

## Subject Line B
[Subject]

## Subject Line C
[Subject]

## Email Body

[The email  keep under 150 words. Personal, direct, value-first.]

## Why This Works
[2-3 bullet points explaining the psychology behind the email]"""

            result = self.claude(prompt, system=system, max_tokens=1500)

            output = f"""# Cold Outreach Email
**Prospect:** {prospect}
**Industry:** {industry}
**Context:** {context}
**Generated:** {ts_display}

---

{result}

---
*Generated by WheellsVerse Sales Agent Bot*
"""
            fname = f"outreach_{ts}.md"
            path = self.save_output(output, fname, ext="md")
            return {"file": str(path), "action": action}

        # ── Follow-up ───────────────────────────────────────────────────────
        elif action == "followup":
            self.logger.info(f"Generating follow-up sequence for: {prospect[:60]}")

            system = (
                "You are an expert sales follow-up strategist. You know that most "
                "deals close after the 3rd-5th touch. Each follow-up must add NEW "
                "value, not just 'checking in.' You vary the format: short, long, "
                "case-study-driven, question-driven, breakup email."
            )

            prompt = f"""Write a 3-email follow-up sequence for:

PROSPECT: {prospect}
INDUSTRY: {industry}
CONTEXT: {context}
PREVIOUS OUTREACH: Cold email about WheellsVerse AI automation platform

Requirements:
- Email 1 (Day 3): Value-add follow-up  share a relevant insight or resource
- Email 2 (Day 7): Social proof follow-up  reference a case study or result
- Email 3 (Day 14): Breakup email  last touch, create urgency without being pushy

For EACH email provide:
## Email [N]  [Type] (Day [X])
**Subject:** [subject line]
**Body:** [full email, under 120 words each]
**Timing note:** [best time to send]"""

            result = self.claude(prompt, system=system, max_tokens=2000)

            output = f"""# Follow-Up Email Sequence
**Prospect:** {prospect}
**Industry:** {industry}
**Context:** {context}
**Generated:** {ts_display}

---

{result}

---
*Generated by WheellsVerse Sales Agent Bot*
"""
            fname = f"followup_{ts}.md"
            path = self.save_output(output, fname, ext="md")
            return {"file": str(path), "action": action}

        # ── Proposal ────────────────────────────────────────────────────────
        elif action == "proposal":
            self.logger.info(f"Generating business proposal for: {prospect[:60]}")

            system = (
                "You are a senior sales consultant who has closed millions in B2B deals. "
                "You write proposals that make the ROI undeniable and the decision obvious. "
                "You mirror the client's language, lead with their problem, and make the "
                "investment feel small compared to the value. Structure: Executive Summary, "
                "The Challenge, The Solution, Expected Results, Investment, Next Steps."
            )

            prompt = f"""Write a comprehensive business proposal for:

PROSPECT: {prospect}
INDUSTRY: {industry}
THEIR SITUATION: {context}
SOLUTION: WheellsVerse AI Automation Platform

Include:
1. **Executive Summary** (3-4 sentences)
2. **Understanding Your Challenge** (empathetic, specific)
3. **The Cost of Doing Nothing** (quantify the pain)
4. **Our Solution** (3-phase implementation plan)
5. **Expected Results** (ROI table with before/after metrics)
6. **Investment Options** (3 tiers: Starter, Growth, Enterprise)
7. **Why WheellsVerse** (3 differentiators)
8. **Next Steps** (3 clear action items)
9. **FAQ** (5 questions they are thinking but not asking)

Make the ROI numbers realistic for {industry}."""

            result = self.claude(prompt, system=system, max_tokens=3000)

            output = f"""# Business Proposal
**Prepared For:** {prospect}
**Industry:** {industry}
**Prepared By:** WheellsVerse
**Date:** {ts_display}

---

{result}

---
*Generated by WheellsVerse Sales Agent Bot*
"""
            fname = f"proposal_{ts}.md"
            path = self.save_output(output, fname, ext="md")
            return {"file": str(path), "action": action}

        else:
            raise ValueError(f"Unknown action: {action}. Use outreach, followup, or proposal.")


# ─── CLI Entry Point ──────────────────────────────────────────────────────────
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="AI Sales Agent Bot")
    parser.add_argument("--action", type=str, default="outreach",
                        choices=["outreach", "followup", "proposal"])
    parser.add_argument("--prospect", type=str, default=None)
    parser.add_argument("--context", type=str, default=None)
    parser.add_argument("--industry", type=str, default=None)
    args = parser.parse_args()

    bot = SalesAgentBot()
    result = bot.execute(action=args.action, prospect=args.prospect,
                         context=args.context, industry=args.industry)
    print(f"\nOutput: {result['file']}")
    print(f"Action: {result['action']}")
