#!/usr/bin/env python3
"""
Bot #36 — Negotiation Strategy Assistant
Category: Sales
Purpose: Build negotiation strategies, scripts, BATNA analysis, and counter-offer
         frameworks for sales deals, partnerships, and contracts.
"""
import os
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot  # noqa: E402


class NegotiationAssistantBot(BaseBot):

    def __init__(self):
        super().__init__("36_negotiation_assistant", "sales")

    def run(self, negotiation_context: str = None, your_goals: str = None,
            their_likely_goals: str = None, deal_value: str = None,
            your_leverage: str = None, **kwargs):

        cfg = self.config
        negotiation_context = negotiation_context or cfg.get("negotiation_context",
            "Client wants 40% discount on WheellsVerse annual plan")
        your_goals = your_goals or cfg.get("your_goals",
            "maintain pricing integrity, close the deal, get a 12-month commitment")
        their_likely_goals = their_likely_goals or cfg.get("their_likely_goals",
            "reduce budget impact, minimize risk, get flexibility to cancel")
        deal_value = deal_value or cfg.get("deal_value", "$4,997/year")
        your_leverage = your_leverage or cfg.get("your_leverage",
            "uniquely solves their stated problem, competitors are more expensive")

        self.logger.info(f"Building negotiation strategy: {negotiation_context}")

        system = (
            "You are a negotiation strategist and sales coach trained in principled "
            "negotiation (Harvard Method), SPIN selling, and deal-closing psychology. "
            "You approach every negotiation as a problem-solving exercise — finding "
            "solutions that both parties feel good about. You never recommend giving "
            "discounts without getting something in return. You teach 'expand the pie' "
            "tactics before 'split the pie' tactics."
        )

        prompt = f"""Build a complete negotiation strategy for:

SITUATION: {negotiation_context}
YOUR GOALS: {your_goals}
THEIR LIKELY GOALS: {their_likely_goals}
DEAL VALUE: {deal_value}
YOUR LEVERAGE: {your_leverage}

## NEGOTIATION ANALYSIS

### BATNA (Best Alternative to Negotiated Agreement)
- **Your BATNA:** [What happens if this deal doesn't close]
- **Their BATNA:** [What alternatives they have]
- **Power assessment:** [Who has more leverage and why]

### INTERESTS VS POSITIONS
- **Their stated position:** [What they're asking for]
- **Their underlying interests:** [What they actually want/fear]
- **Your position:** [What you're offering]
- **Your interests:** [What you actually need]

**Key Insight:** [Where interests align — this is where the deal gets done]

## NEGOTIATION STRATEGY

### Opening Move
[How to respond to their first ask — what to say first, exactly]

### Value Expansion Tactics (Before Price Discussion)
3 ways to increase perceived value before touching price:
1. [Tactic + exact script]
2. [Tactic + exact script]
3. [Tactic + exact script]

### Trade-Off Menu (Never Give — Always Trade)
Instead of discounts, offer trades:
| Give (concession) | Get (what you require in return) | Value to Them | Value to You |
[5-7 trade pairs — discount, payment terms, features, timeline, etc.]

## NEGOTIATION SCRIPTS

### When they ask for a discount:
```
[Exact response — don't say yes, don't say no, reframe]
```

### When they say "we can't afford it":
```
[Exact response — ROI reframe + alternative structure]
```

### When they threaten to go to a competitor:
```
[Exact response — confident, not defensive]
```

### When they ask for a free trial extension:
```
[Exact response with alternative offer]
```

### The Closing Script (After Agreement):
```
[Exact language to confirm the deal and move to next steps]
```

## CONCESSION STRATEGY
If you must concede on price, here's how:
- **First concession:** [What to offer and how to frame it]
- **Second concession:** [If needed — smaller, with bigger ask in return]
- **Walk-away point:** [The line you won't cross and why]

## DEAL STRUCTURE ALTERNATIVES
3 alternative deal structures that solve their budget concern without losing value:
1. [Structure] — How it works + benefit to them + benefit to you
2. [Structure]
3. [Structure]

## POST-NEGOTIATION CHECKLIST
5 things to do immediately after agreement to prevent buyer's remorse"""

        result = self.ai(prompt, system=system,
                         model=os.getenv("OPENAI_MODEL", "gpt-4o"),
                         max_tokens=2500)

        from datetime import datetime as _dt
        ts = _dt.now().strftime("%Y%m%d_%H%M%S")
        safe_ctx = self.slugify(negotiation_context, 25)

        output = f"""# Negotiation Strategy
**Situation:** {negotiation_context}
**Deal Value:** {deal_value}
**Your Goals:** {your_goals}
**Generated:** {_dt.now().strftime('%Y-%m-%d %H:%M')}

---

{result}

---
*Generated by WheellsVerse Negotiation Assistant Bot*
"""
        path = self.save_output(output, f"negotiation_{safe_ctx}_{ts}.md", ext="md")
        self.logger.info(f"Negotiation strategy saved → {path}")
        return {"file": str(path), "context": negotiation_context, "deal_value": deal_value}


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Negotiation Strategy Assistant")
    parser.add_argument("--context", type=str, default=None)
    parser.add_argument("--goals", type=str, default=None)
    parser.add_argument("--theirs", type=str, default=None)
    parser.add_argument("--value", type=str, default=None)
    parser.add_argument("--leverage", type=str, default=None)
    args = parser.parse_args()
    bot = NegotiationAssistantBot()
    result = bot.execute(negotiation_context=args.context, your_goals=args.goals,
                         their_likely_goals=args.theirs, deal_value=args.value,
                         your_leverage=args.leverage)
    print(f"\n✅ Negotiation Strategy: {result['file']}")
