#!/usr/bin/env python3
"""
Bot #13 — Market Trend Analyzer
Category: Marketing
Purpose: Analyze market trends in a niche, identify opportunities, and generate
         a trend-driven content and business strategy report.
"""
import os
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot  # noqa: E402


class TrendAnalyzerBot(BaseBot):

    def __init__(self):
        super().__init__("13_trend_analyzer", "marketing")

    def run(self, niche: str = None, timeframe: str = None,
            platforms: str = None, goal: str = None, **kwargs):

        cfg = self.config
        niche = niche or cfg.get("niche", "AI automation for entrepreneurs")
        timeframe = timeframe or cfg.get("timeframe", "2025 Q1-Q2")
        platforms = platforms or cfg.get("platforms", "TikTok, YouTube, Twitter/X, LinkedIn")
        goal = goal or cfg.get("goal", "content strategy and product ideas")

        self.logger.info(f"Analyzing trends for: {niche} | {timeframe}")

        system = (
            "You are a market research analyst and trend forecaster who specializes in "
            "identifying emerging opportunities before they peak. You combine social media "
            "signal analysis, search trend data, competitor research, and consumer behavior "
            "insights to give actionable intelligence. Your reports are specific, data-informed, "
            "and directly tied to business and content opportunities."
        )

        prompt = f"""Conduct a comprehensive market trend analysis for:

NICHE: {niche}
TIMEFRAME: {timeframe}
PLATFORMS TO ANALYZE: {platforms}
GOAL: {goal}

## 1. TREND OVERVIEW
**The Big Picture:** What's happening in "{niche}" right now?
- Top 3 macro trends shaping this niche in {timeframe}
- What's driving these trends (technology, culture, economy, regulation)
- Where this niche is heading in the next 6-12 months

## 2. RISING TRENDS (Early-Stage Opportunities)
List 5 trends that are gaining traction but not yet saturated:
For each:
- **Trend name:** [name]
- **Evidence:** Why you believe this is rising (search volume signals, viral content, news)
- **Audience:** Who is driving this trend
- **Opportunity window:** How much time before this peaks
- **Content angle:** How to cover this NOW

## 3. PEAK TRENDS (High Volume, High Competition)
List 3 trends currently at peak — how to compete or differentiate:
- What's already saturated
- The unique angle that can still break through

## 4. DECLINING TRENDS (What to Avoid)
3 trends that are losing momentum — why and what replaced them

## 5. PLATFORM-BY-PLATFORM BREAKDOWN
For each platform in "{platforms}":
- Top 3 content formats performing in {niche}
- Posting frequency sweet spot
- Emerging content styles gaining traction
- Top creators/accounts to study in this niche

## 6. KEYWORD & SEARCH OPPORTUNITY
10 trending search terms in {niche} with:
| Keyword | Trend Direction | Content Opportunity | Competition Level |

## 7. CONTENT CALENDAR IDEAS
15 specific content ideas based on rising trends — ready to execute

## 8. BUSINESS OPPORTUNITIES
3 product/service gaps these trends reveal:
- The gap
- The audience pain point
- A possible solution
- Revenue model

## 9. 30-DAY ACTION PLAN
Prioritized steps to capitalize on the top trend identified."""

        result = self.ai(prompt, system=system,
                         model=os.getenv("OPENAI_MODEL_FAST", "gpt-4o-mini"),
                         max_tokens=3000)

        from datetime import datetime as _dt
        ts = _dt.now().strftime("%Y%m%d_%H%M%S")
        safe_niche = self.slugify(niche, 30)

        output = f"""# Market Trend Analysis: {niche}
**Timeframe:** {timeframe}
**Platforms:** {platforms}
**Goal:** {goal}
**Generated:** {_dt.now().strftime('%Y-%m-%d %H:%M')}

---

{result}

---
*Generated by WheellsVerse Trend Analyzer Bot*
"""
        path = self.save_output(output, f"trends_{safe_niche}_{ts}.md", ext="md")
        self.logger.info(f"Trend analysis saved → {path}")
        return {"file": str(path), "niche": niche, "timeframe": timeframe}


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Market Trend Analyzer")
    parser.add_argument("--niche", type=str, default=None)
    parser.add_argument("--timeframe", type=str, default="2025 Q2")
    parser.add_argument("--platforms", type=str, default="TikTok, YouTube, Twitter/X")
    parser.add_argument("--goal", type=str, default="content strategy")
    args = parser.parse_args()
    bot = TrendAnalyzerBot()
    result = bot.execute(niche=args.niche, timeframe=args.timeframe,
                         platforms=args.platforms, goal=args.goal)
    print(f"\n✅ Trend Report: {result['file']}")
