#!/usr/bin/env python3
"""
bots/specialized/72_stock_investing_content_creator/bot.py
Creates engaging stock investing content that educates beginners and drives Robinhood signups.
Revenue goal: Drive Robinhood signups and Amazon investment book purchases.
"""
import os
import sys
import random
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot  # noqa: E402

ROBINHOOD_URL = os.getenv("AFFILIATE_ROBINHOOD_URL", "https://join.robinhood.com/IRhjrdSej2Ms7117979PpUNgqcMUkCW7g1")
COINBASE_URL = os.getenv("AFFILIATE_COINBASE_URL", "https://coinbase.com/join/IRZL3QBqT2Fa7117979C7RLARc7WFdWBH1")
AMAZON_TAG = os.getenv("AFFILIATE_AMAZON_TAG", "wheellsverse-20")

STOCK_TOPICS = [
    "How to start investing in stocks with $100 — a beginner's guide",
    "Index funds vs individual stocks: which is better for beginners?",
    "What is dollar-cost averaging and how can it grow your wealth?",
    "Top 5 commission-free stock investing apps compared in 2025",
    "How to read a stock chart for the first time — simplified",
    "Dividend investing explained: earn passive income from stocks",
    "ETFs vs mutual funds: the key differences every investor must know",
    "How to build a diversified stock portfolio with $500",
    "The power of compound interest: why starting early matters",
    "Stock market basics: what every first-time investor needs to know in 2025",
    "How to invest in the S&P 500 — the ultimate beginner's guide",
    "Growth stocks vs value stocks: which strategy fits your goals?",
]


class StockInvestingContentCreatorBot(BaseBot):
    """Creates engaging, educational stock investing content that converts readers into investors."""

    def __init__(self):
        super().__init__("72_stock_investing_content_creator", "specialized")

    def run(self, topic: str = None, audience_level: str = "beginner", **kwargs):
        cfg = self.config
        topic = topic or cfg.get("default_topic") or random.choice(STOCK_TOPICS)
        audience_level = audience_level or cfg.get("audience_level", "beginner")
        self.logger.info(f"Running {self.name}: {topic}")

        system_str = (
            "You are a professional financial educator and investment content writer. "
            "You specialize in making stock market investing approachable for everyday people. "
            "You explain complex concepts with simple analogies, real examples, and clear steps. "
            "Your content is accurate, actionable, and always prioritizes reader understanding "
            "over jargon. You naturally recommend tools and resources that genuinely help readers."
        )

        prompt = f"""Write a comprehensive, SEO-optimized stock investing blog post on:

TOPIC: "{topic}"
AUDIENCE LEVEL: {audience_level}

## Article Requirements
- **Length:** 900-1200 words
- **Tone:** Clear, confident, encouraging — financial advisor meets best friend
- **SEO:** Keyword-rich H1, topic in intro and subheadings naturally

## Required Sections

**1. Magnetic H1 Headline** (include primary keyword, promise a clear outcome)

**2. Hook Introduction** (2-3 sentences: the problem this solves, why it matters today)

**3. Main Educational Content** (3-4 H2 sections):
   - Real examples with specific numbers (e.g., "if you invested $100/month at 8% for 30 years...")
   - Step-by-step breakdowns where relevant
   - Common mistakes to avoid
   - Data points and statistics (use realistic estimates)

**4. Tool & Platform Recommendations** (natural, helpful context):
   - [Robinhood]({ROBINHOOD_URL}): Best for commission-free stock + ETF investing — mention free stock for new users
   - [Coinbase]({COINBASE_URL}): If the topic touches crypto as part of a diversified portfolio
   - [Investment books on Amazon](https://www.amazon.com/s?k=stock+investing+beginners+books&tag={AMAZON_TAG}): For readers who want to go deeper

**5. Quick-Start Action Plan** (3-5 concrete steps readers can take today)

**6. CTA** (guide readers to the most relevant next step)

Use plain English. Avoid jargon without explanation. Make readers feel confident, not overwhelmed."""

        result = self.ai(
            prompt, system=system_str,
            model=os.getenv("OPENAI_MODEL", "gpt-4o"),
            max_tokens=2500
        )

        from datetime import datetime as _dt
        ts = _dt.now().strftime("%Y%m%d_%H%M%S")
        safe_topic = "".join(c if c.isalnum() else "_" for c in topic[:40])

        output = f"""# {topic}
*Generated: {_dt.now().strftime('%Y-%m-%d %H:%M')} | WheellsVerse Investing Content*

---

{result}

---
*Generated by WheellsVerse Stock Investing Content Creator — {self.name}*
"""
        path = self.save_output(output, f"stocks_{safe_topic}_{ts}.md", ext="md")
        self.logger.info(f"Saved: {path}")
        return {"file": str(path), "bot": self.name}


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Stock Investing Content Creator Bot")
    parser.add_argument("--topic", type=str, default=None, help="Investing topic to cover")
    parser.add_argument("--audience", type=str, default="beginner", choices=["beginner", "intermediate", "advanced"])
    args = parser.parse_args()
    bot = StockInvestingContentCreatorBot()
    result = bot.execute(topic=args.topic, audience_level=args.audience)
    print(f"\n✅ Output: {result['file']}")
