#!/usr/bin/env python3
"""
Bot #1 — Content Generator
Category: Marketing
Purpose: Generate high-quality content (blog posts, articles, social posts,
         product descriptions) for any topic and brand voice.
Inputs:  topic, content_type, word_count, tone, keywords
Outputs: Markdown file saved to outputs/marketing/01_content_generator/
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot


class ContentGeneratorBot(BaseBot):
    """Generates marketing content using GPT."""

    def __init__(self):
        super().__init__("01_content_generator", "marketing")

    def run(self, topic: str = None, content_type: str = None,
            word_count: int = None, tone: str = None,
            keywords: str = None, **kwargs):

        # Load defaults from config
        cfg = self.config
        topic        = topic or cfg.get("default_topic", "AI automation for entrepreneurs")
        content_type = content_type or cfg.get("default_type", "blog_post")
        word_count   = word_count or cfg.get("word_count", 800)
        tone         = tone or cfg.get("tone", "professional, engaging, bold")
        keywords     = keywords or cfg.get("keywords", "AI, automation, productivity")

        self.logger.info(f"Generating {content_type} on: {topic}")

        content_types = {
            "blog_post":     "a comprehensive, SEO-optimized blog post",
            "article":       "a detailed editorial article",
            "social_post":   "an engaging social media post",
            "product_desc":  "a compelling product description",
            "email":         "a persuasive marketing email",
            "landing_page":  "landing page copy with headline, benefits, and CTA",
            "press_release": "a professional press release",
            "ad_copy":       "short, punchy ad copy with headline and body"
        }

        ct_label = content_types.get(content_type, "content")

        system = (
            "You are an expert content marketer and copywriter. "
            "You write compelling, high-converting content that ranks well on search engines. "
            "Always include a strong headline, engaging intro, and clear call-to-action."
        )

        prompt = f"""Create {ct_label} with the following specifications:

TOPIC: {topic}
TARGET WORD COUNT: ~{word_count} words
TONE: {tone}
KEYWORDS TO INCLUDE: {keywords}

Requirements:
- Start with a powerful headline (H1)
- Write an engaging hook in the first paragraph
- Structure with clear H2/H3 subheadings
- Include actionable insights and value
- End with a clear call-to-action
- Optimize for readability (short paragraphs, bullet points where appropriate)
- Naturally incorporate keywords without stuffing

Format as Markdown."""

        content = self.ai(prompt, system=system, max_tokens=2500)

        # Build the full document
        output = f"""# Content Generated by WheellsVerse Bot
**Topic:** {topic}
**Type:** {content_type}
**Tone:** {tone}
**Keywords:** {keywords}
**Generated:** {self._now()}

---

{content}

---
*Generated by WheellsVerse Content Generator Bot*
"""
        # Save output
        safe_topic = "".join(c if c.isalnum() else "_" for c in topic[:40])
        fname = f"{content_type}_{safe_topic}.md"
        path = self.save_output(output, fname, ext="md")

        self.logger.info(f"Content saved → {path}")
        return {"file": str(path), "word_count": len(content.split()),
                "type": content_type, "topic": topic}

    def _now(self):
        from datetime import datetime
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def batch_generate(self, topics: list, content_type: str = "blog_post") -> list:
        """Generate content for multiple topics in one call."""
        results = []
        for topic in topics:
            try:
                result = self.execute(topic=topic, content_type=content_type)
                results.append(result)
            except Exception as e:
                results.append({"error": str(e), "topic": topic})
        return results


# ─── CLI Entry Point ──────────────────────────────────────────────────────────
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Content Generator Bot")
    parser.add_argument("--topic",    type=str, default=None)
    parser.add_argument("--type",     type=str, default="blog_post",
                        choices=["blog_post","article","social_post","product_desc",
                                 "email","landing_page","press_release","ad_copy"])
    parser.add_argument("--words",    type=int, default=800)
    parser.add_argument("--tone",     type=str, default="professional, engaging")
    parser.add_argument("--keywords", type=str, default="AI, automation")
    args = parser.parse_args()

    bot = ContentGeneratorBot()
    result = bot.execute(topic=args.topic, content_type=args.type,
                         word_count=args.words, tone=args.tone,
                         keywords=args.keywords)
    print(f"\n✅ Output: {result['file']}")
    print(f"   Words:  {result['word_count']}")
