#!/usr/bin/env python3
"""
Bot #4 — Ad Copy Generator
Category: Marketing
Purpose: Generate high-converting ad copy for multiple platforms.
Inputs:  product, platform, objective, audience, budget_tier
Outputs: Complete ad copy package (headlines, descriptions, CTAs) for each platform
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from core.base_bot import BaseBot


class AdCopyBot(BaseBot):

    def __init__(self):
        super().__init__("04_ad_copy", "marketing")

    def run(self, product: str = None, platforms: list = None,
            objective: str = None, audience: str = None,
            num_variations: int = None, **kwargs):

        cfg = self.config
        product       = product or cfg.get("product", "WheellsVerse AI Platform")
        platforms     = platforms or cfg.get("platforms", ["facebook", "google", "instagram"])
        objective     = objective or cfg.get("objective", "lead generation")
        audience      = audience or cfg.get("audience", "entrepreneurs 25-45, interested in AI")
        num_variations = num_variations or cfg.get("num_variations", 3)

        self.logger.info(f"Generating ad copy for {product} on {platforms}")

        system = (
            "You are a performance marketing expert who writes direct-response ad copy "
            "that consistently achieves 3-5x ROAS. You understand platform-specific "
            "character limits, best practices, and psychological triggers."
        )

        ad_specs = {
            "facebook": {
                "primary_text": "125 chars visible, 500 max",
                "headline": "40 chars max",
                "description": "30 chars max",
                "formats": "Single Image, Carousel, Video (first 3 secs critical)"
            },
            "google": {
                "headline_1": "30 chars max",
                "headline_2": "30 chars max",
                "headline_3": "30 chars max",
                "description_1": "90 chars max",
                "description_2": "90 chars max",
                "formats": "Responsive Search Ads, Performance Max"
            },
            "instagram": {
                "caption": "125 chars visible, 2200 max",
                "cta": "Learn More, Shop Now, Sign Up, Get Quote",
                "formats": "Square 1:1, Story 9:16, Reel"
            },
            "linkedin": {
                "headline": "70 chars max",
                "description": "100 chars max",
                "intro_text": "150 chars visible",
                "formats": "Single Image, Carousel, Video"
            },
            "tiktok": {
                "text_overlay": "100 chars max",
                "hook": "First 3 seconds critical",
                "formats": "9:16 vertical video, 15-60 seconds"
            }
        }

        all_copy = []

        for platform in platforms:
            specs = ad_specs.get(platform.lower(), {})
            specs_str = "\n".join([f"  - {k}: {v}" for k, v in specs.items()])

            prompt = f"""Create {num_variations} ad copy variations for {platform.upper()} with these specs:

PRODUCT/SERVICE: {product}
CAMPAIGN OBJECTIVE: {objective}
TARGET AUDIENCE: {audience}
PLATFORM SPECS:
{specs_str}

For EACH variation provide:
1. VARIATION NAME (e.g., "Pain-Point Angle", "Social Proof Angle", "FOMO Angle")
2. All required text fields with character counts in parentheses
3. IMAGE/VIDEO CONCEPT description
4. TARGETING SUGGESTION (interests, behaviors, lookalikes)
5. EXPECTED CTR ESTIMATE (based on industry benchmarks)

Use psychological triggers: urgency, social proof, fear of missing out, 
curiosity, authority, reciprocity. Make CTAs action-oriented and specific."""

            copy = self.ai(prompt, system=system, max_tokens=2000)
            all_copy.append(f"\n## {platform.upper()} ADS\n\n{copy}")

        output_md = f"""# Ad Copy Package — {product}
**Platforms:** {', '.join(platforms)}
**Objective:** {objective}
**Audience:** {audience}
**Variations per platform:** {num_variations}
**Generated:** {self._now()}

---

{''.join(all_copy)}

---

## 📋 SPLIT TESTING STRATEGY
- Start with 3 variations per ad set
- Run for minimum 3-5 days with $10-20/day budget
- Kill underperformers (CTR < 1%) after 1000 impressions
- Scale winners (ROAS > 2x) by increasing budget 20% every 48 hours
- Refresh creative every 3-4 weeks to avoid ad fatigue

---
*Generated by WheellsVerse Ad Copy Bot*
"""
        safe = product.replace(" ", "_")[:30]
        path = self.save_output(output_md, f"ads_{safe}.md", ext="md")
        self.logger.info(f"Ad copy saved → {path}")
        return {"file": str(path), "platforms": platforms, "variations": num_variations}

    def _now(self):
        from datetime import datetime
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Ad Copy Generator")
    parser.add_argument("--product",   type=str, default=None)
    parser.add_argument("--platforms", type=str, default="facebook,google,instagram")
    parser.add_argument("--objective", type=str, default="lead generation")
    parser.add_argument("--audience",  type=str, default=None)
    parser.add_argument("--variations",type=int, default=3)
    args = parser.parse_args()
    platforms = [p.strip() for p in args.platforms.split(",")]
    bot = AdCopyBot()
    result = bot.execute(product=args.product, platforms=platforms,
                         objective=args.objective, audience=args.audience,
                         num_variations=args.variations)
    print(f"\n✅ Ad Copy: {result['file']}")
